const APP_KEY="inf125.v6.sheetCache";
const SETTINGS_KEY="inf125.v6.appsScriptSettings";
const LAST_IMPORT_KEY="inf125.v6.lastImportSnapshot";
const now=()=>new Date().toISOString();
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const norm=v=>String(v??"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]/g,"");
const clone=v=>JSON.parse(JSON.stringify(v));
const makeId=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2,8)}`;

const sheetDefs={
  Dashboard:{key:"dashboard",label:"Dashboard",icon:"◈",fields:["KPI","Value","V6 Launch Checklist","Owner","Status","Target Date","Notes"]},
  Course_Config:{key:"courseConfig",label:"Course Config",icon:"⚙",fields:["Setting","Value","Notes"],idField:"Setting"},
  V6_Settings:{key:"v6Settings",label:"V6 Settings",icon:"☷",fields:["Setting","Value","Notes"],idField:"Setting"},
  Weeks:{key:"weeks",label:"Weeks",icon:"W",fields:["Week","Module Title","Focus Topic","Learning Goal Summary","Student-Facing Overview","Module Status","AI Generation Status","Review Status","Publish Status","Notes"],idField:"Week",required:["Week","Module Title"]},
  Course_Calendar:{key:"courseCalendar",label:"Course Calendar",icon:"📅",fields:["Calendar ID","Week","Meeting Date","Session Label","Topic","Modality","Location","Prep Notes","Canvas Module Name","Publish Notes"],idField:"Calendar ID",prefix:"cal"},
  Activities:{key:"activities",label:"Activities",icon:"✎",fields:["Activity ID","Week","Title","Activity Type","Estimated Minutes","Student Instructions","Instructor Notes","Materials / Links","Status","Notes"],idField:"Activity ID",prefix:"act",required:["Week","Title"]},
  Assessments:{key:"assessments",label:"Assessments",icon:"☑",fields:["Assessment ID","Week","Title","Canvas Item Type","Points","Due Date","Description","Submission Type","Rubric Needed?","Status","Notes"],idField:"Assessment ID",prefix:"asm",required:["Week","Title"]},
  Learning_Objectives:{key:"learningObjectives",label:"Learning Objectives",icon:"◎",fields:["Objective ID","Course Outcome","Weekly Objective","Week","Bloom Level","Assessment Link","GenEd / Accreditation Link","Status","Notes"],idField:"Objective ID",prefix:"obj",required:["Week","Weekly Objective"]},
  AI_Drafts:{key:"aiDrafts",label:"AI Drafts",icon:"AI",fields:["Draft ID","Week","Source Type","Canvas Item Type","Canvas Title","Draft HTML","Plain Text Summary","AI Prompt Snapshot","Generation Status","Review Status","Publish Status","Canvas ID","Canvas URL","Created At","Updated At","Approved By","Notes"],idField:"Draft ID",prefix:"draft",required:["Canvas Title"]},
  Canvas_Item_Map:{key:"canvasItemMap",label:"Canvas Item Map",icon:"↔",fields:["Map ID","Week","Source ID","Source Type","Canvas Item Type","Canvas Title","Canvas ID","Canvas URL","Canvas Module ID","Last Sync","Sync Status","Duplicate Strategy","Notes"],idField:"Map ID",prefix:"map"},
  Publishing_Log:{key:"publishingLog",label:"Publishing Log",icon:"↗",fields:["Timestamp","Action","Week","Canvas Item Type","Canvas Title","Publish Status","Canvas ID","Canvas URL","Message"]},
  Faculty_Signup:{key:"facultySignup",label:"Faculty Signup",icon:"＋",fields:["Signup ID","Timestamp","Name","Email","Role / Department","Week","Preferred Date","Topic / Contribution","Status","Notes"],idField:"Signup ID",prefix:"signup"},
  Faculty_Feedback:{key:"facultyFeedback",label:"Faculty Feedback",icon:"💬",fields:["Feedback ID","Timestamp","Name","Email","Role / Department","Week","Focus Topic","Feedback Type","Feedback","Follow Up Requested?","Status","Notes"],idField:"Feedback ID",prefix:"feedback"},
  Lists:{key:"lists",label:"Lists / Dropdown Values",icon:"▤",fields:["Statuses","Canvas Item Types","Activity Types","Bloom Levels","Yes/No"]}
};
const sheetNames=Object.keys(sheetDefs), keyToSheet=Object.fromEntries(sheetNames.map(n=>[sheetDefs[n].key,n]));
const nav=["dashboard","settings","generator","spreadsheetImport",...sheetNames.map(n=>sheetDefs[n].key)];
const labels={dashboard:"Dashboard",settings:"Settings",generator:"Generate Content",spreadsheetImport:"Spreadsheet Import",...Object.fromEntries(sheetNames.map(n=>[sheetDefs[n].key,sheetDefs[n].label]))};
const listDefaults={"Statuses":"Draft\nNeeds Review\nApproved\nPublished\nSent to Canvas\nRejected\nError","Canvas Item Types":"Page\nAssignment\nDiscussion\nQuiz\nRubric\nAnnouncement","Activity Types":"Discussion\nLab\nReflection\nReading\nWorkshop","Bloom Levels":"Remember\nUnderstand\nApply\nAnalyze\nEvaluate\nCreate","Yes/No":"Yes\nNo"};
const defaults={
  dashboard:[{KPI:"Sheet connection",Value:"Local cache until Apps Script is configured",Status:"Draft",Notes:"GitHub Pages calls Apps Script only."},{"V6 Launch Checklist":"Connect Apps Script Web App",Owner:"Instructor",Status:"Needs Review","Target Date":"2027-01-05",Notes:"Store URL only; secrets stay in Apps Script Properties."}],
  courseConfig:[{Setting:"Course",Value:"INF 125: Social Media and Society",Notes:"Institutional Memory: applied, inclusive, current examples."},{Setting:"Course ID",Value:"INF125",Notes:"Used in Apps Script payloads."}],
  v6Settings:[{Setting:"AI generation tone",Value:"Warm, practical, student-facing",Notes:"Gemini key stays in Apps Script Properties."},{Setting:"Sync source",Value:"Google Sheet via Apps Script",Notes:"localStorage is fallback/cache."}],
  weeks:Array.from({length:8},(_,i)=>({Week:i+1,"Module Title":["Platform Society","Identity & Community","Algorithms & Attention","Creator Economies","Misinformation","Data & Privacy","Online Harm & Moderation","Social Media Futures Studio"][i],"Focus Topic":"INF 125 social media analysis","Learning Goal Summary":"Analyze social platforms using course concepts.","Student-Facing Overview":"Connect everyday platform experience with evidence-based analysis.","Module Status":i<2?"Approved":"Draft","AI Generation Status":i<2?"Generated":"Not Started","Review Status":i<2?"Approved":"Needs Review","Publish Status":"Not Published",Notes:"Add current examples before teaching."})),
  courseCalendar:[{"Calendar ID":"cal-1",Week:1,"Meeting Date":"2027-01-12","Session Label":"Launch","Topic":"Platform Society",Modality:"Hybrid",Location:"Canvas + Classroom","Prep Notes":"Review syllabus","Canvas Module Name":"Week 1: Platform Society","Publish Notes":"Draft"}],
  activities:[{"Activity ID":"act-1",Week:1,Title:"Platform artifact analysis","Activity Type":"Workshop","Estimated Minutes":35,"Student Instructions":"Select a platform feature and explain its social effects.","Instructor Notes":"Use small groups.","Materials / Links":"Canvas page",Status:"Draft",Notes:"Use Institutional Memory rubric language."}],
  assessments:[{"Assessment ID":"asm-1",Week:1,Title:"Applied Platform Analysis 1","Canvas Item Type":"Assignment",Points:25,"Due Date":"2027-01-19",Description:"Analyze one platform artifact.","Submission Type":"Online text","Rubric Needed?":"Yes",Status:"Needs Review",Notes:"Needs rubric."}],
  learningObjectives:[{"Objective ID":"obj-1","Course Outcome":"Evaluate social impacts of platform design.","Weekly Objective":"Identify platform affordances and constraints.",Week:1,"Bloom Level":"Analyze","Assessment Link":"asm-1","GenEd / Accreditation Link":"Information literacy",Status:"Approved",Notes:"Align quiz questions."}],
  aiDrafts:[],canvasItemMap:[],publishingLog:[],facultySignup:[],facultyFeedback:[],lists:[listDefaults]
};
let settings=loadSettings(); let state=loadState(); let source="Local cache"; let importBook=null, importPlan={};
function loadSettings(){try{return {appsScriptUrl:"",courseId:"INF125",canvasCourseId:"",syncMode:"Draft Only",enableCache:"Yes",...(JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}"))};}catch{return {appsScriptUrl:"",courseId:"INF125",canvasCourseId:"",syncMode:"Draft Only",enableCache:"Yes"};}}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
function loadState(){try{return {...clone(defaults),...(JSON.parse(localStorage.getItem(APP_KEY)||"{}"))};}catch{return clone(defaults);}}
function saveCache(){if(settings.enableCache!=="No")localStorage.setItem(APP_KEY,JSON.stringify(state)); updateSourceBadge();}
function updateSourceBadge(){const b=$("#sourceBadge"); if(b)b.textContent=source;}
function toast(t,m){$("#toastTitle").textContent=t;$("#toastMessage").textContent=m;$("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.remove("show"),3200);}
function statusClass(s){s=String(s||"").toLowerCase();return s.includes("approved")||s.includes("published")||s.includes("sent")||s.includes("success")?"success":s.includes("review")||s.includes("draft")||s.includes("progress")?"warning":s.includes("error")||s.includes("reject")?"danger":"neutral";}

const AppsScriptAPI={
  async request(action,payload={}){ if(!settings.appsScriptUrl) throw new Error("Add an Apps Script Web App URL in Settings first.");
    const body={action,courseId:settings.courseId,canvasCourseId:settings.canvasCourseId,...payload};
    // Apps Script endpoint contract: POST JSON {action, courseId, canvasCourseId, sectionName, row, rowId, payload} and return {ok,data,error}.
    // SECURITY WARNING: Gemini API keys and Canvas tokens must live in Apps Script Properties, never in GitHub Pages JavaScript.
    const res=await fetch(settings.appsScriptUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)});
    const json=await res.json().catch(()=>({ok:false,error:"Apps Script did not return JSON."}));
    if(!res.ok||json.ok===false) throw new Error(json.error||`Apps Script ${action} failed`);
    return json.data ?? json;
  },
  fetchSheetData(sectionName){return this.request("getSheetData",{sectionName});},
  saveSheetRow(sectionName,row){return this.request("saveSheetRow",{sectionName,row});},
  updateSheetRow(sectionName,rowId,row){return this.request("updateSheetRow",{sectionName,rowId,row});},
  deleteSheetRow(sectionName,rowId){return this.request("deleteSheetRow",{sectionName,rowId});},
  generateWithGemini(payload){return this.request("generateWithGemini",payload);},
  publishToCanvas(payload){return this.request("publishToCanvas",payload);},
  getCanvasStatus(canvasItemId){return this.request("getCanvasStatus",{canvasItemId});},
  logPublishingAction(payload){return this.request("logPublishingAction",payload);}
};

function renderNav(){const icons={dashboard:"⌂",settings:"⚙",generator:"✦",spreadsheetImport:"⇪"};$("#nav").innerHTML=`<p class="nav-label">Google Sheet workflow</p>`+nav.map(k=>`<button class="nav-link" data-page="${k}"><span>${icons[k]||sheetDefs[keyToSheet[k]]?.icon||"▤"}</span>${labels[k]}</button>`).join("");}
function navigate(k,hash=true){if(!$("#"+k))k="dashboard"; $$(".page").forEach(p=>p.classList.toggle("active",p.id===k)); $$(".nav-link").forEach(n=>n.classList.toggle("active",n.dataset.page===k)); $("#breadcrumb").textContent=labels[k]; if(hash&&location.hash.slice(1)!==k)history.replaceState(null,"",`#${k}`); $("#sidebar").classList.remove("open");}
function kpis(){return {weeks:state.weeks.length,activities:state.activities.length,assessments:state.assessments.length,objectives:state.learningObjectives.length,drafts:state.aiDrafts.length,approved:state.aiDrafts.filter(d=>d["Review Status"]==="Approved").length,published:state.aiDrafts.filter(d=>["Sent to Canvas","Published"].includes(d["Publish Status"])).length};}
function renderDashboard(){const k=kpis();$("#dashboard").innerHTML=`<div class="page-heading dashboard-heading"><div><p class="eyebrow">DASHBOARD</p><h1>INF 125 Google Sheet command center</h1><p>GitHub Pages front end, Google Sheets course database, Apps Script secure proxy for Gemini and Canvas.</p></div><div class="ai-status"><i></i><span>${esc(source)}<small>${settings.syncMode} · cache ${settings.enableCache}</small></span></div></div><div class="metric-grid">${[[k.weeks,"Weeks"],[k.activities,"Activities"],[k.assessments,"Assessments"],[k.objectives,"Objectives"],[k.drafts,"AI Drafts"],[k.approved,"Approved"],[k.published,"Sent to Canvas"],[state.canvasItemMap.length,"Canvas Map"]].map(([v,l])=>`<article class="metric-card"><span>${l}</span><strong>${v}</strong><small>Workbook aligned</small></article>`).join("")}</div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><div><h2>V6 Launch Checklist</h2><p>Loaded from Dashboard sheet/cache.</p></div><button class="secondary-btn" data-action="syncFromSheet">Refresh from Sheet</button></div>${miniTable(state.dashboard,["V6 Launch Checklist","Owner","Status","Target Date","Notes"])}</section><section class="panel"><h2>Canvas Intelligence</h2>${canvasInsights().map(x=>`<div class="task"><span>✦</span><p>${esc(x)}<small>Calculated from Weeks, AI_Drafts, Canvas_Item_Map, and Publishing_Log.</small></p></div>`).join("")}</section></div>`;}
function canvasInsights(){return [`${state.weeks.filter(w=>!["Sent to Canvas","Published"].includes(w["Publish Status"])).length} weeks are not published`,`${state.aiDrafts.filter(d=>d["Review Status"]!=="Approved").length} drafts need review`,`${state.assessments.filter(a=>String(a["Rubric Needed?"]).toLowerCase()==="yes").length} assessments need rubrics`,`${state.canvasItemMap.length} Canvas items mapped through Apps Script`];}
function miniTable(rows,fields){return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${f.includes("Status")?`<span class="status ${statusClass(r[f])}">${esc(r[f])}</span>`:esc(r[f])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function renderSettings(){ $("#settings").innerHTML=`<div class="page-heading"><div><p class="eyebrow">SETTINGS</p><h1>Google Sheet + Apps Script connection</h1><p>Store only non-secret settings locally. Gemini and Canvas secrets stay in Apps Script Properties.</p></div><span class="status ${settings.appsScriptUrl?'success':'warning'}">${settings.appsScriptUrl?'Connected URL saved':'Local cache only'}</span></div><form class="panel form-panel" id="settingsForm"><div class="form-grid"><label class="wide">Apps Script Web App URL<input name="appsScriptUrl" value="${esc(settings.appsScriptUrl)}" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Course ID<input name="courseId" value="${esc(settings.courseId)}"></label><label>Canvas Course ID<input name="canvasCourseId" value="${esc(settings.canvasCourseId)}"></label><label>Sync mode<select name="syncMode">${["Read Only","Draft Only","Full Publish"].map(v=>`<option ${settings.syncMode===v?'selected':''}>${v}</option>`).join("")}</select></label><label>Enable local cache<select name="enableCache">${["Yes","No"].map(v=>`<option ${settings.enableCache===v?'selected':''}>${v}</option>`).join("")}</select></label></div><div class="button-row"><button class="primary-btn" type="submit">Save Settings</button><button class="secondary-btn" type="button" data-action="syncFromSheet">Sync from Google Sheet</button><button class="secondary-btn" type="button" data-action="saveAll">Save changes to Google Sheet</button></div><p class="note">Expected Apps Script actions: getSheetData, saveSheetRow, updateSheetRow, deleteSheetRow, generateWithGemini, publishToCanvas, getCanvasStatus, logPublishingAction.</p></form>`;}
function listValues(field){return String((state.lists[0]||listDefaults)[field]||listDefaults[field]||"").split(/\n|,/).map(s=>s.trim()).filter(Boolean);}
function renderSheet(sheet){const def=sheetDefs[sheet], key=def.key, rows=state[key]||[];$("#"+key).innerHTML=`<div class="page-heading"><div><p class="eyebrow">${sheet}</p><h1>${def.label}</h1><p>Displays and edits the ${sheet} Google Sheet tab. Local cache is fallback.</p></div><div class="button-row"><button class="secondary-btn" data-action="refreshSheet" data-sheet="${sheet}">Refresh from Sheet</button><button class="primary-btn" data-add-row="${sheet}">Add row</button></div></div><div class="panel"><div class="panel-header"><div class="filter-row"><input data-filter="${key}" placeholder="Search"><select data-week-filter="${key}"><option value="">All weeks</option>${[...new Set(rows.map(r=>r.Week).filter(Boolean))].map(w=>`<option>${esc(w)}</option>`).join("")}</select><select data-status-filter="${key}"><option value="">All statuses</option>${listValues("Statuses").map(s=>`<option>${esc(s)}</option>`).join("")}</select></div><button class="secondary-btn" data-action="saveSheet" data-sheet="${sheet}">Save this tab to Sheet</button></div><div id="${key}Rows">${renderRows(sheet,rows)}</div></div>`;}
function rowIndex(key,row,fallback){const i=(state[key]||[]).indexOf(row);return i>=0?i:fallback;}
function renderRows(sheet,rows){const def=sheetDefs[sheet],key=def.key;if(!rows.length)return `<div class="empty-state"><span>□</span><h3>No rows</h3><p>Add rows, sync from Google Sheet, or import a spreadsheet backup.</p></div>`;return `<div class="table-wrap"><table><thead><tr>${def.fields.map(f=>`<th>${esc(f)}</th>`).join("")}<th>Sync</th><th>Actions</th></tr></thead><tbody>${rows.map((r,i)=>{const idx=rowIndex(key,r,i);return `<tr>${def.fields.map(f=>`<td>${cell(key,idx,f,r[f])}</td>`).join("")}<td><button class="text-btn" data-push-row="${sheet}" data-index="${idx}">Push row</button></td><td><div class="button-row"><button class="text-btn" data-dup-row="${sheet}" data-index="${idx}">Duplicate</button><button class="text-btn danger-text" data-del-row="${sheet}" data-index="${idx}">Delete</button>${sheet==="AI_Drafts"?draftButtons(r,idx):""}</div></td></tr>`;}).join("")}</tbody></table></div>`;}
function cell(key,i,f,v){const selectMap={"Canvas Item Type":"Canvas Item Types","Activity Type":"Activity Types","Bloom Level":"Bloom Levels","Rubric Needed?":"Yes/No","Follow Up Requested?":"Yes/No"}; if(f.includes("Status"))return `<select data-edit="${key}" data-index="${i}" data-field="${esc(f)}">${listValues("Statuses").map(o=>`<option ${o==v?'selected':''}>${esc(o)}</option>`).join("")}</select>`; if(selectMap[f])return `<select data-edit="${key}" data-index="${i}" data-field="${esc(f)}">${listValues(selectMap[f]).map(o=>`<option ${o==v?'selected':''}>${esc(o)}</option>`).join("")}</select>`; return `<textarea data-edit="${key}" data-index="${i}" data-field="${esc(f)}">${esc(v)}</textarea>`;}
function draftButtons(r,i){return `<button class="text-btn" data-approve-draft="${i}">Approve</button><button class="text-btn" data-send-canvas="${i}" ${r["Review Status"]!=="Approved"||["Sent to Canvas","Published"].includes(r["Publish Status"])?"disabled":""}>Send to Canvas</button>`;}
function renderGenerator(){const sourceOptions=["Weeks","Activities","Assessments","Learning_Objectives"].map(s=>`<option>${s}</option>`).join("");$("#generator").innerHTML=`<div class="page-heading"><div><p class="eyebrow">GEMINI VIA APPS SCRIPT</p><h1>Generate course content</h1><p>Browser sends context to Apps Script; Apps Script calls Gemini securely.</p></div></div><div class="two-column"><form class="panel" id="geminiForm"><div class="form-grid"><label>Week<select id="genWeek">${state.weeks.map(w=>`<option>${esc(w.Week)}</option>`).join("")}</select></label><label>Source section<select id="genSection">${sourceOptions}</select></label><label>Output format<select id="genOutput"><option>Canvas Page</option><option>Assignment</option><option>Discussion</option><option>Quiz</option><option>Rubric</option><option>Announcement</option></select></label><label>Tone<input id="genTone" value="Warm, practical, student-facing"></label><label class="wide">Prompt<textarea id="genPrompt">Create INF 125 content aligned to the selected week and workbook rows.</textarea></label></div><button class="primary-btn full" type="submit">Generate with Gemini via Apps Script</button><p class="note">Payload: { action:"generateWithGemini", courseId, sectionName, selectedRows, prompt, outputType }</p></form><section class="panel"><h2>Generation result</h2><div id="geminiOutput" class="empty-state"><span>✦</span><h3>No generated draft yet</h3><p>Returned drafts are saved into AI_Drafts.</p></div></section></div>`;}
function renderImport(){const targets=sheetNames.map(s=>`<option>${s}</option>`).join("");$("#spreadsheetImport").innerHTML=`<div class="page-heading"><div><p class="eyebrow">SPREADSHEET IMPORT BACKUP</p><h1>Import workbook or CSV</h1><p>Backup option when Apps Script is unavailable. Imported rows save to cache and can be pushed to Google Sheet.</p></div></div><div class="two-column"><section class="panel"><label class="drop-zone" id="dropZone"><span>⇪</span><strong>Drop .xlsx, .xls, or .csv here</strong><small>Parsing happens locally in your browser.</small><input id="spreadsheetFile" type="file" accept=".xlsx,.xls,.csv,text/csv"></label><div class="form-grid"><label>Import mode<select id="importMode"><option value="merge">Merge with existing data</option><option value="replace">Replace existing data</option><option value="draft">Import as draft data only</option></select></label><label>Default CSV target<select id="csvTarget">${targets}</select></label></div><div class="button-row"><button class="primary-btn" id="runImportBtn">Import selected rows</button><button class="secondary-btn" id="undoImportBtn">Undo Last Import</button></div><div id="importSummary" class="note">Choose a file to detect sheets and columns.</div></section><section class="panel"><h2>Sheet and column mapping</h2><div id="sheetMappings" class="import-mappings empty-state"><span>⇪</span><h3>No file loaded</h3><p>Mappings appear here.</p></div></section></div><section class="panel" style="margin-top:20px"><div class="panel-header"><h2>Preview</h2><span id="previewCount" class="status neutral">0 rows</span></div><div id="importPreview"></div></section>`; bindImport();}
function renderAll(){renderNav();renderDashboard();renderSettings();renderGenerator();renderImport();sheetNames.forEach(renderSheet);updateSourceBadge();}

async function syncFromSheet(){try{setLoading(true,"Syncing from Google Sheet...");const loaded={};for(const sheet of sheetNames){const data=await AppsScriptAPI.fetchSheetData(sheet);loaded[sheetDefs[sheet].key]=Array.isArray(data)?data:(data.rows||[]);}state={...state,...loaded};source="Google Sheet";saveCache();renderAll();toast("Synced from Google Sheet","Local cache updated.");}catch(e){source="Local cache (Apps Script unavailable)";updateSourceBadge();toast("Sync failed",e.message);}finally{setLoading(false);}}
async function saveAllToSheet(){if(settings.syncMode==="Read Only")return toast("Read Only mode","Switch sync mode before saving."); if(!confirm("Save all local rows to Google Sheet via Apps Script?"))return; try{setLoading(true,"Saving all tabs...");for(const sheet of sheetNames){for(const row of state[sheetDefs[sheet].key]||[])await AppsScriptAPI.saveSheetRow(sheet,row);}source="Google Sheet + local cache";saveCache();toast("Saved to Google Sheet","All workbook tabs pushed through Apps Script.");}catch(e){toast("Save failed",e.message);}finally{setLoading(false);}}
async function pushRow(sheet,index){try{const def=sheetDefs[sheet],row=state[def.key][index];const rowId=def.idField?row[def.idField]:index;await AppsScriptAPI.updateSheetRow(sheet,rowId,row);toast("Row pushed",`${sheet} row saved to Google Sheet.`);}catch(e){toast("Push failed",e.message);}}
async function refreshSheet(sheet){try{const data=await AppsScriptAPI.fetchSheetData(sheet);state[sheetDefs[sheet].key]=Array.isArray(data)?data:(data.rows||[]);source="Google Sheet";saveCache();renderAll();toast("Sheet refreshed",sheet);}catch(e){toast("Refresh failed",e.message);}}
function setLoading(on,msg="Loading..."){document.body.classList.toggle("loading",on); if(on)toast("Working",msg);}
async function generateGemini(e){e.preventDefault();const section=$("#genSection").value,week=$("#genWeek").value,key=sheetDefs[section].key;const selectedRows=(state[key]||[]).filter(r=>String(r.Week)===String(week));const payload={sectionName:section,selectedRows,prompt:$("#genPrompt").value,tone:$("#genTone").value,outputType:$("#genOutput").value};let result;try{result=await AppsScriptAPI.generateWithGemini(payload);toast("Generated with Gemini","Draft returned from Apps Script.");}catch(err){result={"Draft HTML":`<h2>${esc(payload.outputType)} for Week ${esc(week)}</h2><p>Local fallback draft because Apps Script returned: ${esc(err.message)}</p>`,"Plain Text Summary":"Local fallback draft. Configure Apps Script for Gemini.","AI Prompt Snapshot":JSON.stringify({action:"generateWithGemini",courseId:settings.courseId,...payload},null,2),"Generation Status":"Fallback Draft"};toast("Using fallback draft",err.message);}const draft={"Draft ID":makeId("draft"),Week:week,"Source Type":section,"Canvas Item Type":payload.outputType,"Canvas Title":`${payload.outputType} Week ${week}`,"Draft HTML":result.draftHtml||result["Draft HTML"]||"","Plain Text Summary":result.plainTextSummary||result["Plain Text Summary"]||"","AI Prompt Snapshot":result.promptSnapshot||result["AI Prompt Snapshot"]||payload.prompt,"Generation Status":result.generationStatus||result["Generation Status"]||"Generated","Review Status":"Needs Review","Publish Status":"Not Published","Canvas ID":"","Canvas URL":"","Created At":now(),"Updated At":now(),"Approved By":"",Notes:"Generated through Apps Script workflow or local fallback."};state.aiDrafts.unshift(draft);saveCache();renderAll();navigate("aiDrafts");}
async function sendCanvas(i){const d=state.aiDrafts[i];if(!d||d["Review Status"]!=="Approved")return toast("Approval required","Approve the AI Draft before publishing.");if(["Sent to Canvas","Published"].includes(d["Publish Status"]))return toast("Already sent","This draft already has a Canvas publish status.");const payload={canvasCourseId:settings.canvasCourseId,canvasItemType:d["Canvas Item Type"],canvasTitle:d["Canvas Title"],draftHtml:d["Draft HTML"],week:d.Week,moduleName:`Week ${d.Week}`};let res;try{res=await AppsScriptAPI.publishToCanvas(payload);}catch(e){res={canvasId:`mock-${Date.now()}`,canvasUrl:`https://canvas.example.edu/courses/${settings.canvasCourseId||"INF125"}/items/mock`,message:`Local simulated publish because Apps Script returned: ${e.message}`};toast("Simulated Canvas publish",e.message);}d["Publish Status"]="Sent to Canvas";d["Canvas ID"]=res.canvasId||res["Canvas ID"]||res.id;d["Canvas URL"]=res.canvasUrl||res["Canvas URL"]||res.url;d["Updated At"]=now();const map={"Map ID":makeId("map"),Week:d.Week,"Source ID":d["Draft ID"],"Source Type":"AI_Drafts","Canvas Item Type":d["Canvas Item Type"],"Canvas Title":d["Canvas Title"],"Canvas ID":d["Canvas ID"],"Canvas URL":d["Canvas URL"],"Canvas Module ID":res.canvasModuleId||`week-${d.Week}`,"Last Sync":now(),"Sync Status":"Sent to Canvas","Duplicate Strategy":"Update by Source ID",Notes:"Published through Apps Script workflow or local simulation."};const mi=state.canvasItemMap.findIndex(m=>m["Source ID"]===d["Draft ID"]);mi>=0?state.canvasItemMap[mi]=map:state.canvasItemMap.push(map);const log={Timestamp:now(),Action:"publishToCanvas",Week:d.Week,"Canvas Item Type":d["Canvas Item Type"],"Canvas Title":d["Canvas Title"],"Publish Status":"Sent to Canvas","Canvas ID":d["Canvas ID"],"Canvas URL":d["Canvas URL"],Message:res.message||"Canvas publish completed."};state.publishingLog.unshift(log);try{await AppsScriptAPI.logPublishingAction(log);}catch{}saveCache();renderAll();toast("Canvas status updated",d["Canvas Title"]);}

function ensureRow(sheet,row){const def=sheetDefs[sheet];if(def.idField&&!row[def.idField])row[def.idField]=makeId(def.prefix||"row");if(sheet==="AI_Drafts"){row["Created At"]||=now();row["Updated At"]||=now();}def.fields.filter(f=>f.includes("Status")).forEach(f=>row[f]||=(f==="Publish Status"?"Not Published":"Draft"));return row;}
function same(a,b){return String(a??"").trim().toLowerCase()===String(b??"").trim().toLowerCase();}
function findDup(sheet,row){const def=sheetDefs[sheet],rows=state[def.key]||[];if(def.idField&&row[def.idField])return rows.findIndex(r=>same(r[def.idField],row[def.idField]));if(sheet==="Weeks")return rows.findIndex(r=>same(r.Week,row.Week));if(["Activities","Assessments"].includes(sheet))return rows.findIndex(r=>same(r.Week,row.Week)&&same(r.Title,row.Title));if(sheet==="Learning_Objectives")return rows.findIndex(r=>same(r.Week,row.Week)&&same(r["Weekly Objective"],row["Weekly Objective"]));if(sheet==="AI_Drafts")return rows.findIndex(r=>same(r.Week,row.Week)&&same(r["Canvas Title"],row["Canvas Title"]));return -1;}
function detectSheet(name){const n=norm(name);return sheetNames.find(s=>norm(s)===n||norm(sheetDefs[s].label)===n)||"";}
function detectCol(h,fields){const n=norm(h);return fields.find(f=>norm(f)===n)||"";}
function bindImport(){const input=$("#spreadsheetFile"),drop=$("#dropZone");if(!input)return;input.onchange=e=>readSpreadsheet(e.target.files[0]);["dragenter","dragover"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add("drag");}));["dragleave","drop"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove("drag");}));drop.addEventListener("drop",e=>readSpreadsheet(e.dataTransfer.files[0]));$("#runImportBtn").onclick=runImport;$("#undoImportBtn").onclick=undoImport;}
async function readSpreadsheet(file){if(!file)return;try{const ext=file.name.split('.').pop().toLowerCase(),sheets={};if(ext==="csv"){const txt=await file.text();sheets[$("#csvTarget").value]=csvToRows(txt);}else{if(!window.XLSX)throw new Error("SheetJS failed to load from CDN.");const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});wb.SheetNames.forEach(n=>sheets[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:"",raw:false}));}importBook={file:file.name,sheets};buildMappings();toast("Spreadsheet loaded",`${Object.keys(sheets).length} sheet(s) detected.`);}catch(e){$("#importSummary").textContent=e.message;toast("Import error",e.message);}}
function csvToRows(txt){const lines=txt.replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean);const parse=l=>{let a=[],c="",q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'&&l[i+1]==='"'){c+='"';i++;}else if(ch==='"')q=!q;else if(ch===','&&!q){a.push(c);c="";}else c+=ch;}a.push(c);return a;};const h=parse(lines.shift()||"");return lines.map(l=>Object.fromEntries(parse(l).map((v,i)=>[h[i]||`Column ${i+1}`,v])));}
function buildMappings(){importPlan={};$("#sheetMappings").classList.remove("empty-state");$("#sheetMappings").innerHTML=Object.entries(importBook.sheets).map(([name,rows],i)=>{const sheet=detectSheet(name)||name,def=sheetDefs[sheet]||sheetDefs[$("#csvTarget").value],headers=[...new Set(rows.flatMap(Object.keys))];importPlan[name]={sheet:sheetDefs[sheet]?sheet:$("#csvTarget").value,enabled:!!def,cols:Object.fromEntries(headers.map(h=>[h,detectCol(h,def.fields)]))};return `<div class="mapping-card" data-sheet="${esc(name)}"><label><input type="checkbox" data-map-enabled checked> Import <strong>${esc(name)}</strong> <small>${rows.length} rows</small></label><label>Map to tab<select data-map-sheet>${sheetNames.map(s=>`<option ${importPlan[name].sheet===s?'selected':''}>${s}</option>`).join("")}</select></label><div class="column-map" id="cols-${i}"></div></div>`;}).join("");refreshColMaps();$("#sheetMappings").onchange=e=>{const card=e.target.closest("[data-sheet]");if(!card)return;const name=card.dataset.sheet;if(e.target.matches("[data-map-enabled]"))importPlan[name].enabled=e.target.checked;if(e.target.matches("[data-map-sheet]")){importPlan[name].sheet=e.target.value;Object.keys(importPlan[name].cols).forEach(h=>importPlan[name].cols[h]=detectCol(h,sheetDefs[e.target.value].fields));refreshColMaps();}if(e.target.matches("[data-col]"))importPlan[name].cols[e.target.dataset.header]=e.target.value;previewImport();};previewImport();}
function refreshColMaps(){Object.entries(importBook.sheets).forEach(([name,rows],i)=>{const p=importPlan[name],fields=sheetDefs[p.sheet].fields,heads=[...new Set(rows.flatMap(Object.keys))],el=$(`#cols-${i}`);el.innerHTML=heads.map(h=>`<label>${esc(h)}<select data-col data-header="${esc(h)}"><option value="">Skip</option>${fields.map(f=>`<option ${p.cols[h]===f?'selected':''}>${esc(f)}</option>`).join("")}</select></label>`).join("");});previewImport();}
function normalizedImports(){if(!importBook)return[];const out=[];Object.entries(importBook.sheets).forEach(([name,rows])=>{const p=importPlan[name];if(!p?.enabled)return;rows.forEach(raw=>{const r={};Object.entries(p.cols).forEach(([h,f])=>{if(f)r[f]=raw[h];});ensureRow(p.sheet,r);out.push({sheet:p.sheet,row:r,warnings:(sheetDefs[p.sheet].required||[]).filter(f=>!r[f]).map(f=>`Missing ${f}`)});});});return out;}
function previewImport(){const rows=normalizedImports();$("#previewCount").textContent=`${rows.length} rows`;$("#importSummary").innerHTML=`Detected <strong>${Object.keys(importBook?.sheets||{}).length}</strong> sheet(s). Review mappings before import.`;$("#importPreview").innerHTML=rows.length?miniTable(rows.slice(0,20).map(x=>({Tab:x.sheet,Warnings:x.warnings.join('; '),...x.row})),["Tab","Warnings",...Object.keys(rows[0].row).slice(0,6)]):"<p class='note'>No mapped rows yet.</p>";}
function runImport(){const rows=normalizedImports();if(!rows.length)return toast("Nothing to import","Map at least one row.");const snap={};rows.forEach(({sheet,row})=>{const key=sheetDefs[sheet].key;snap[key]??=clone(state[key]);if($("#importMode").value==="replace"&&!snap[key]._replaced){state[key]=[];snap[key]._replaced=true;}if($("#importMode").value==="draft")sheetDefs[sheet].fields.filter(f=>f.includes("Status")).forEach(f=>row[f]=f==="Publish Status"?"Not Published":"Draft");const dupe=findDup(sheet,row);dupe>=0?state[key][dupe]={...state[key][dupe],...row}:state[key].push(row);});localStorage.setItem(LAST_IMPORT_KEY,JSON.stringify(snap));source="Local cache + spreadsheet import";saveCache();renderAll();toast("Import complete",`${rows.length} row(s) imported.`);}
function undoImport(){const raw=localStorage.getItem(LAST_IMPORT_KEY);if(!raw)return toast("Nothing to undo","No import snapshot found.");const snap=JSON.parse(raw);Object.entries(snap).forEach(([k,v])=>{delete v._replaced;state[k]=v;});localStorage.removeItem(LAST_IMPORT_KEY);saveCache();renderAll();toast("Import undone","Restored previous cached rows.");}
function download(name,text,type="text/plain"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function csv(rows){if(!rows.length)return"";const f=[...new Set(rows.flatMap(Object.keys))];return[f.join(","),...rows.map(r=>f.map(k=>`"${String(r[k]??"").replace(/"/g,'""')}"`).join(","))].join("\n");}

document.addEventListener("click",e=>{const nav=e.target.closest("[data-page]");if(nav)navigate(nav.dataset.page);const a=e.target.closest("[data-action]");if(a){if(a.dataset.action==="syncFromSheet")syncFromSheet();if(a.dataset.action==="saveAll")saveAllToSheet();if(a.dataset.action==="refreshSheet")refreshSheet(a.dataset.sheet);if(a.dataset.action==="saveSheet")saveSheet(a.dataset.sheet);}const add=e.target.closest("[data-add-row]");if(add){const s=add.dataset.addRow,key=sheetDefs[s].key,row={};sheetDefs[s].fields.forEach(f=>row[f]="");ensureRow(s,row);state[key].push(row);saveCache();renderAll();}const dup=e.target.closest("[data-dup-row]");if(dup){const s=dup.dataset.dupRow,key=sheetDefs[s].key,row=clone(state[key][dup.dataset.index]);if(sheetDefs[s].idField)row[sheetDefs[s].idField]=makeId(sheetDefs[s].prefix||"row");state[key].splice(+dup.dataset.index+1,0,row);saveCache();renderAll();}const del=e.target.closest("[data-del-row]");if(del&&confirm("Delete this row locally and from the Sheet if connected?")){const s=del.dataset.delRow,key=sheetDefs[s].key,row=state[key][del.dataset.index];state[key].splice(+del.dataset.index,1);saveCache();renderAll();AppsScriptAPI.deleteSheetRow(s,row[sheetDefs[s].idField]).catch(err=>toast("Sheet delete skipped",err.message));}const push=e.target.closest("[data-push-row]");if(push)pushRow(push.dataset.pushRow,+push.dataset.index);const app=e.target.closest("[data-approve-draft]");if(app){const d=state.aiDrafts[app.dataset.approveDraft];d["Review Status"]="Approved";d["Approved By"]="Instructor";d["Updated At"]=now();saveCache();renderAll();}const send=e.target.closest("[data-send-canvas]");if(send)sendCanvas(+send.dataset.sendCanvas);});
async function saveSheet(sheet){try{for(const row of state[sheetDefs[sheet].key])await AppsScriptAPI.saveSheetRow(sheet,row);toast("Sheet saved",sheet);}catch(e){toast("Save failed",e.message);}}
document.addEventListener("input",e=>{if(e.target.matches("[data-edit]")){const {edit,index,field}=e.target.dataset;state[edit][index][field]=e.target.value;if(edit==="aiDrafts")state[edit][index]["Updated At"]=now();saveCache();}if(e.target.matches("[data-filter],[data-week-filter],[data-status-filter]")){const key=e.target.dataset.filter||e.target.dataset.weekFilter||e.target.dataset.statusFilter;const q=$(`[data-filter='${key}']`)?.value.toLowerCase()||"",w=$(`[data-week-filter='${key}']`)?.value||"",st=$(`[data-status-filter='${key}']`)?.value||"",sheet=keyToSheet[key];const rows=(state[key]||[]).filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!w||String(r.Week)===w)&&(!st||Object.entries(r).some(([k,v])=>k.includes("Status")&&String(v)===st)));$(`#${key}Rows`).innerHTML=renderRows(sheet,rows);}});
document.addEventListener("submit",e=>{if(e.target.id==="settingsForm"){e.preventDefault();settings={...settings,...Object.fromEntries(new FormData(e.target).entries())};saveSettings();renderAll();toast("Settings saved","Apps Script connection settings stored locally.");}if(e.target.id==="geminiForm")generateGemini(e);});
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#syncFromSheetBtn").onclick=syncFromSheet;$("#saveAllBtn").onclick=saveAllToSheet;$("#backupBtn").onclick=()=>download("inf125-command-center-backup.json",JSON.stringify(state,null,2),"application/json");$("#restoreInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;state={...clone(defaults),...JSON.parse(await f.text())};source="Restored local backup";saveCache();renderAll();};
window.addEventListener("hashchange",()=>navigate(location.hash.slice(1)||"dashboard",false));
renderAll();navigate(location.hash.slice(1)||"dashboard",false); if(settings.appsScriptUrl) syncFromSheet(); else toast("Local cache mode","Add an Apps Script Web App URL in Settings to sync Google Sheets.");
