const STORE = "inf125.canvas.builder.v1";
const SETTINGS = "inf125.canvas.builder.settings";
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const today = () => new Date().toISOString();
let settings = JSON.parse(localStorage.getItem(SETTINGS) || "{}");
let data = JSON.parse(localStorage.getItem(STORE) || "null") || structuredClone(window.INF125_SAMPLE_DATA);

function save(){ localStorage.setItem(STORE, JSON.stringify(data)); }
function saveSettings(){ localStorage.setItem(SETTINGS, JSON.stringify(settings)); }
function toast(msg, type="ok"){ const t=$("#toast"); t.textContent=msg; t.className=`toast show ${type}`; setTimeout(()=>t.className="toast",3500); }
async function api(action, payload={}){
  if(!settings.appsScriptUrl) throw new Error("Add the Google Apps Script Web App URL in Settings first.");
  const res = await fetch(settings.appsScriptUrl, { method:"POST", headers:{"Content-Type":"text/plain;charset=utf-8"}, body:JSON.stringify({ action, sheetId:settings.sheetId, canvasCourseId:settings.canvasCourseId, canvasBaseUrl:settings.canvasBaseUrl, ...payload }) });
  const json = await res.json().catch(()=>({ok:false,error:"Apps Script did not return JSON."}));
  if(!res.ok || json.ok === false) throw new Error(json.error || `${action} failed`);
  return json.data || json;
}
function statusClass(v){ v=String(v).toLowerCase(); return v.includes("approved")||v.includes("sent")||v.includes("complete")||v.includes("ready") ? "good" : v.includes("need")||v.includes("draft") ? "warn" : "muted"; }
function kpis(){ return {modules:new Set(data.content.map(r=>r.module)).size, items:data.content.length, drafts:data.content.filter(r=>r.aiDraft).length, needs:data.content.filter(r=>r.facultyStatus!=="Approved").length, approved:data.content.filter(r=>r.facultyStatus==="Approved").length, sent:data.content.filter(r=>r.canvasStatus==="Sent"||r.canvasStatus==="Complete").length}; }
function renderDashboard(){ const k=kpis(); $("#dashboard").innerHTML=`<div class="section-head"><div><p class="eyebrow">Dashboard</p><h2>Course production status</h2><p>Summary of your Google Sheet-backed INF 125 workflow.</p></div><span class="pill">${settings.appsScriptUrl?"Apps Script configured":"Sample/local mode"}</span></div><div class="cards">${[["Total modules",k.modules],["Total content items",k.items],["Drafts generated",k.drafts],["Items needing approval",k.needs],["Items approved",k.approved],["Items sent to Canvas",k.sent]].map(([l,v])=>`<article class="card"><span>${l}</span><strong>${v}</strong></article>`).join("")}</div><div class="panel"><h3>Safe architecture</h3><p>GitHub Pages stores only public course data, non-secret settings, and local demo cache. Gemini API keys and Canvas tokens belong only in Google Apps Script Script Properties.</p></div>`; }
function actionButtons(r){ return `<div class="row-actions"><button data-action="generate" data-id="${r.id}">Generate Draft</button><button data-action="improve" data-id="${r.id}">Improve Draft</button><button data-action="approve" data-id="${r.id}">Approve</button><button data-action="send" data-id="${r.id}">Send to Canvas</button><button data-action="complete" data-id="${r.id}">Mark Complete</button></div>`; }
function renderTable(){ const cols=["week","unit","module","contentType","title","slos","genEdOutcomes","readings","discussionQuestions","smallAssignment","curriculum","aiDraft","facultyStatus","sendToCanvas","canvasStatus"]; $("#content").innerHTML=`<div class="section-head"><div><p class="eyebrow">Course Content Table</p><h2>Spreadsheet source of truth</h2></div><button id="syncContent">Refresh from Apps Script</button></div><div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(label(c))}</th>`).join("")}<th>Workflow</th></tr></thead><tbody>${data.content.map(r=>`<tr>${cols.map(c=>`<td>${cell(r,c)}</td>`).join("")}<td>${actionButtons(r)}</td></tr>`).join("")}</tbody></table></div>`; }
function cell(r,c){ if(c==="facultyStatus"||c==="canvasStatus") return `<span class="badge ${statusClass(r[c])}">${esc(r[c])}</span>`; if(c==="aiDraft") return r[c] ? `<button data-action="view" data-id="${r.id}">View draft</button>` : "—"; if(c==="sendToCanvas") return r[c] ? "Yes" : "No"; return esc(r[c]); }
function label(c){ return c.replace(/([A-Z])/g," $1").replace(/^./,m=>m.toUpperCase()).replace("Slos","SLOs"); }
function renderBuilder(){ const weeks=[...new Set(data.content.map(r=>r.week))]; $("#builder").innerHTML=`<div class="section-head"><div><p class="eyebrow">Module Builder View</p><h2>Generate Canvas-ready weekly content</h2><p>Each card can create outcomes, overview pages, readings, discussions, assignments, curriculum, and Canvas HTML.</p></div></div><div class="module-grid">${weeks.map(w=>{const rows=data.content.filter(r=>r.week===w); return `<article class="module-card"><span>Week ${w}</span><h3>${esc(rows[0].module)}</h3><p>${esc(rows[0].curriculum)}</p><div class="chips"><b>SLOs ${esc(rows[0].slos)}</b><b>${esc(rows[0].genEdOutcomes)}</b></div>${["moduleOverview","readings","discussionQuestions","smallAssignment","curriculum","canvasPage"].map(t=>`<button data-action="generate" data-kind="${t}" data-id="${rows[0].id}">Generate ${label(t)}</button>`).join("")}</article>`}).join("")}</div>`; }
function renderAssignments(){ $("#assignments").innerHTML=`<div class="section-head"><div><p class="eyebrow">Major Assignments</p><h2>Approved INF 125 signature assessments</h2></div></div><div class="assignment-grid">${data.majorAssignments.map(a=>`<article class="panel assignment"><h3>${esc(a.title)}</h3>${["purpose","instructions","deliverables","rubric","sloMapping","genEdMapping","canvasSettings"].map(k=>`<h4>${label(k)}</h4><p>${esc(a[k])}</p>`).join("")}<button data-major="${esc(a.title)}">Generate Canvas Assignment Page</button></article>`).join("")}</div>`; }
function renderPreview(){ const ready=data.content.filter(r=>r.facultyStatus==="Approved"); $("#preview").innerHTML=`<div class="section-head"><div><p class="eyebrow">Canvas Export Preview</p><h2>Review before publishing</h2><p>Only approved content appears here.</p></div></div>${ready.map(r=>`<article class="panel preview"><h3>${esc(r.title)}</h3><dl><dt>Canvas module name</dt><dd>Week ${r.week}: ${esc(r.module)}</dd><dt>Page / assignment / discussion title</dt><dd>${esc(r.title)}</dd><dt>Type</dt><dd>${esc(r.contentType)}</dd><dt>Points</dt><dd>${esc(r.points || "N/A")}</dd><dt>Due date placeholder</dt><dd>${esc(r.dueDate || "TBD")}</dd><dt>Description/body content</dt><dd>${r.aiDraft || `<p>${esc(r.curriculum)}</p>`}</dd></dl><button data-action="send" data-id="${r.id}">Send approved item to Canvas</button></article>`).join("") || `<div class="panel">No approved items are ready for Canvas export.</div>`}`; }
function renderSettings(){ $("#settings").innerHTML=`<div class="section-head"><div><p class="eyebrow">Settings</p><h2>Local browser settings only</h2><p>Never enter Gemini API keys or Canvas tokens here.</p></div></div><form id="settingsForm" class="panel form"><label>Google Apps Script Web App URL<input name="appsScriptUrl" value="${esc(settings.appsScriptUrl||"")}" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Google Sheet ID<input name="sheetId" value="${esc(settings.sheetId||"")}"></label><label>Canvas Course ID<input name="canvasCourseId" value="${esc(settings.canvasCourseId||"")}"></label><label>Canvas Base URL<input name="canvasBaseUrl" value="${esc(settings.canvasBaseUrl||"")}" placeholder="https://nku.instructure.com"></label><button class="gold">Save settings to localStorage</button></form><div class="panel warning"><strong>Security note:</strong> Gemini API keys and Canvas API tokens must be stored in Apps Script Script Properties, not in GitHub Pages code or localStorage.</div>`; }
function render(){ renderDashboard(); renderTable(); renderBuilder(); renderAssignments(); renderPreview(); renderSettings(); }
async function workflow(action, id, kind){ const row=data.content.find(r=>r.id===id); if(!row) return; try{ if(action==="view") return openModal(`<h2>${esc(row.title)}</h2>${row.aiDraft || "<p>No draft yet.</p>"}`); if(action==="approve"){ row.facultyStatus="Approved"; await api("approveItem",{row}).catch(()=>null); toast("Item approved."); }
 else if(action==="complete"){ row.canvasStatus="Complete"; await api("markComplete",{row}).catch(()=>null); toast("Item marked complete."); }
 else if(action==="send"){ if(row.facultyStatus!=="Approved") throw new Error("Faculty Status must be Approved before sending to Canvas."); const preview={moduleName:`Week ${row.week}: ${row.module}`, title:row.title, type:row.contentType, points:row.points, dueDate:row.dueDate, body:row.aiDraft||row.curriculum}; const res=await api("sendToCanvas",{row, preview}); row.canvasStatus="Sent"; row.canvasUrl=res.canvasUrl||""; toast("Approved content sent to Canvas."); }
 else if(action==="generate"||action==="improve"){ const res=await api(action==="generate"?"generateDraft":"improveDraft",{row, kind:kind||row.contentType}); row.aiDraft=res.html||res.draftHtml||fallbackDraft(row,kind); row.facultyStatus="Needs Approval"; toast(`${action==="generate"?"Draft generated":"Draft improved"}.`); }
 save(); render(); } catch(e){ if(action==="generate"||action==="improve"){ row.aiDraft=fallbackDraft(row,kind); row.facultyStatus="Needs Approval"; save(); render(); toast("Apps Script unavailable; created local sample draft.","warn"); } else toast(e.message,"bad"); } }
function fallbackDraft(r,kind="Canvas content"){ return `<h2>${esc(r.title)}</h2><p><strong>${esc(kind)}</strong> draft grounded in INF 125 AI Literacy, NKU Individual & Society, Gen Ed ${esc(r.genEdOutcomes)}, and SLOs ${esc(r.slos)}.</p><h3>Overview</h3><p>${esc(r.curriculum)}</p><h3>Readings</h3><p>${esc(r.readings)}</p><h3>Discussion</h3><p>${esc(r.discussionQuestions)}</p><h3>Practice</h3><p>${esc(r.smallAssignment)}</p>`; }
function openModal(html){ $("#modalContent").innerHTML=html; $("#modal").classList.add("open"); }
document.addEventListener("click", async e=>{ const tab=e.target.closest("[data-tab]"); if(tab){ document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===tab.dataset.tab)); document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===tab)); } const a=e.target.closest("[data-action]"); if(a) workflow(a.dataset.action,a.dataset.id,a.dataset.kind); if(e.target.id==="loadSampleBtn"){ data=structuredClone(window.INF125_SAMPLE_DATA); save(); render(); toast("Sample INF 125 data loaded."); } if(e.target.id==="syncBtn"||e.target.id==="syncContent"){ try{ const res=await api("getCourseData",{}); data={...data,...res}; save(); render(); toast("Course data loaded from Apps Script."); }catch(err){ toast(err.message,"bad"); } } if(e.target.dataset.major){ const a=data.majorAssignments.find(x=>x.title===e.target.dataset.major); openModal(`<h2>${esc(a.title)}</h2><p>${esc(a.instructions)}</p><pre>${esc(a.rubric)}</pre>`); } });
$("#closeModal").onclick=()=>$("#modal").classList.remove("open");
document.addEventListener("submit", e=>{ if(e.target.id==="settingsForm"){ e.preventDefault(); settings=Object.fromEntries(new FormData(e.target).entries()); saveSettings(); render(); toast("Settings saved locally."); }});
render();
