const STORE = "inf125.canvas.builder.v2";
const SETTINGS = "inf125.canvas.builder.settings.v2";
const VERSIONS = ["Master Shell", "In-Person", "Online/Hybrid", "WE Lead CS Licensed"];
const VERSION_KEYS = {"Master Shell":"masterShellCourseId","In-Person":"inPersonCourseId","Online/Hybrid":"onlineHybridCourseId","WE Lead CS Licensed":"weLeadCsCourseId"};
const VERSION_META = {
  "Master Shell": {mode:"Master", brand:"NKU gold-copy branding", policy:"Approved NKU INF 125 policy language", prompt:"Preserve approved INF 125 Master Shell content as the gold copy."},
  "In-Person": {mode:"In-Person", brand:"NKU classroom delivery", policy:"Attendance, participation, classroom discussion", prompt:"Adapt this approved INF 125 content for an in-person college course. Preserve the approved SLOs, Gen Ed mappings, and assessment purpose. Add classroom activities, live discussion prompts, and instructor facilitation notes."},
  "Online/Hybrid": {mode:"Online/Hybrid", brand:"NKU online/hybrid delivery", policy:"Online participation and weekly checklist expectations", prompt:"Adapt this approved INF 125 content for online or hybrid delivery. Preserve the approved SLOs, Gen Ed mappings, and assessment purpose. Add asynchronous instructions, weekly checklist language, online discussion prompts, and recorded demo placeholders."},
  "WE Lead CS Licensed": {mode:"Licensed Partner", brand:"WE Lead CS partner-ready delivery", policy:"Remove NKU-only operational language; add licensing placeholders", prompt:"Adapt this approved INF 125 content for a licensed external partner delivery version. Preserve the approved curriculum structure, SLOs, and learning intent. Remove NKU-only operational language where appropriate. Add facilitator guidance, implementation notes, and partner customization placeholders."}
};
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const today = () => new Date().toISOString();
let settings = JSON.parse(localStorage.getItem(SETTINGS) || "{}");
let data = normalizeData(JSON.parse(localStorage.getItem(STORE) || "null") || structuredClone(window.INF125_SAMPLE_DATA));
let workingVersion = settings.workingVersion || "Master Shell";
function normalizeData(d){ d.courseVersions ||= VERSIONS.map(v=>({name:v, canvasCourseId:"", deliveryMode:VERSION_META[v].mode, brandingRules:VERSION_META[v].brand, policyRules:VERSION_META[v].policy, syncStatus:v==="Master Shell"?"Master Approved":"Synced"})); d.content=(d.content||[]).map(r=>normalizeRow(r)); return d; }
function normalizeRow(r){ const v=r.courseVersion||"Master Shell"; const inc=r.includeInVersion||r.includeInVersions||"Master Shell, In-Person, Online/Hybrid, WE Lead CS Licensed"; return {...r, courseVersion:v, includeInVersion:inc, canvasTargetCourseId:r.canvasTargetCourseId||"", deliveryMode:r.deliveryMode||VERSION_META[v]?.mode||"", partnerLicenseVersion:r.partnerLicenseVersion||"", customizationNotes:r.customizationNotes||"", brandingNotes:r.brandingNotes||"", policyNotes:r.policyNotes||"", visibility:r.visibility||"Visible", publishStatus:r.publishStatus|| (r.facultyStatus==="Approved"?"Ready":"Draft"), canvasExportStatus:r.canvasExportStatus||r.canvasStatus||"Not Sent", canvasExportDate:r.canvasExportDate||"", canvasItemUrl:r.canvasItemUrl||r.canvasUrl||"", masterShellSourceId:r.masterShellSourceId||r.id, versionSyncStatus:r.versionSyncStatus||"Synced"}; }
function save(){ localStorage.setItem(STORE, JSON.stringify(data)); }
function saveSettings(){ settings.workingVersion=workingVersion; localStorage.setItem(SETTINGS, JSON.stringify(settings)); }
function toast(msg,type="ok"){ const t=$("#toast"); t.textContent=msg; t.className=`toast show ${type}`; setTimeout(()=>t.className="toast",3500); }
async function api(action,payload={}){ if(!settings.appsScriptUrl) throw new Error("Add the Google Apps Script Web App URL in Settings first."); const res=await fetch(settings.appsScriptUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,sheetId:settings.sheetId,canvasBaseUrl:settings.canvasBaseUrl,...payload})}); const json=await res.json().catch(()=>({ok:false,error:"Apps Script did not return JSON."})); if(!res.ok||json.ok===false) throw new Error(json.error||`${action} failed`); return json.data||json; }
function includesVersion(r,v=workingVersion){ return String(r.includeInVersion||"").split(/[,;|]/).map(x=>x.trim()).includes(v) || r.courseVersion===v; }
function rowsFor(v=workingVersion){ return data.content.filter(r=>includesVersion(r,v)); }
function targetCourseId(v=workingVersion){ return settings[VERSION_KEYS[v]] || data.courseVersions.find(x=>x.name===v)?.canvasCourseId || ""; }
function statusClass(v){ v=String(v).toLowerCase(); return v.includes("approved")||v.includes("sent")||v.includes("complete")||v.includes("ready")||v.includes("synced") ? "good" : v.includes("need")||v.includes("draft")||v.includes("out") ? "warn" : "muted"; }
function versionSelector(){ return `<label class="version-select">Working Version <select id="workingVersion">${VERSIONS.map(v=>`<option ${v===workingVersion?"selected":""}>${v}</option>`).join("")}</select></label>`; }
function metrics(v){ const rs=rowsFor(v); return {total:rs.length,draft:rs.filter(r=>["Draft","Needs Approval"].includes(r.facultyStatus)||r.publishStatus==="Draft").length, approved:rs.filter(r=>r.facultyStatus==="Approved"||r.publishStatus==="Approved"||r.publishStatus==="Ready").length, sent:rs.filter(r=>r.canvasExportStatus==="Sent"||r.canvasStatus==="Sent").length, customize:rs.filter(r=>String(r.versionSyncStatus).includes("Customization")||String(r.customizationNotes).trim()).length, out:rs.filter(r=>String(r.versionSyncStatus).includes("Out of Sync")).length}; }
function renderDashboard(){ const cards=VERSIONS.map(v=>{const m=metrics(v); return `<article class="card version-card ${v===workingVersion?'active-version':''}"><span>${esc(v)}</span><strong>${m.total}</strong><small>Draft ${m.draft} · Approved ${m.approved} · Sent ${m.sent}</small><div class="mini"><b>Needs customization: ${m.customize}</b><b>Out of sync: ${m.out}</b></div></article>`}).join(""); const w=metrics(workingVersion); $("#dashboard").innerHTML=`<div class="section-head"><div><p class="eyebrow">Dashboard</p><h2>Version-aware course production</h2><p>Showing ${esc(workingVersion)} content from one approved spreadsheet source of truth.</p></div>${versionSelector()}</div><div class="cards version-cards">${cards}</div><div class="cards">${[["Items in working version",w.total],["Draft items",w.draft],["Approved items",w.approved],["Sent to Canvas",w.sent],["Needs customization",w.customize],["Out of sync",w.out]].map(([l,v])=>`<article class="card"><span>${l}</span><strong>${v}</strong></article>`).join("")}</div><div class="panel warning"><strong>Export rule:</strong> Content can be sent only when Faculty Status is Approved, Include in Version contains ${esc(workingVersion)}, Canvas Target Course ID exists, and Publish Status is Ready or Approved.</div>`; }
function label(c){ return c.replace(/([A-Z])/g," $1").replace(/^./,m=>m.toUpperCase()).replace("Slos","SLOs"); }
function badge(v){ return `<span class="badge ${statusClass(v)}">${esc(v||"—")}</span>`; }
function cell(r,c){ if(["facultyStatus","publishStatus","canvasExportStatus","versionSyncStatus"].includes(c)) return badge(r[c]); if(c==="aiDraft") return r[c]?`<button data-action="view" data-id="${r.id}">View</button>`:"—"; return esc(r[c]); }
function actionButtons(r){ return `<div class="row-actions"><button data-action="version-customize" data-id="${r.id}">Generate Customization</button><button data-action="approve-version" data-id="${r.id}">Approve Version</button><button data-action="preview-export" data-id="${r.id}">Preview Export</button><button data-action="send" data-id="${r.id}">Send to Canvas</button><button data-action="out-sync" data-id="${r.id}">Mark Out of Sync</button></div>`; }
function renderTable(){ const cols=["week","unit","module","contentType","title","courseVersion","includeInVersion","canvasTargetCourseId","deliveryMode","partnerLicenseVersion","customizationNotes","brandingNotes","policyNotes","visibility","facultyStatus","publishStatus","canvasExportStatus","canvasExportDate","canvasItemUrl","masterShellSourceId","versionSyncStatus"]; $("#content").innerHTML=`<div class="section-head"><div><p class="eyebrow">Content Builder</p><h2>Spreadsheet source of truth</h2></div>${versionSelector()}</div><div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${label(c)}</th>`).join("")}<th>Workflow</th></tr></thead><tbody>${rowsFor().map(r=>`<tr>${cols.map(c=>`<td>${cell(r,c)}</td>`).join("")}<td>${actionButtons(r)}</td></tr>`).join("")}</tbody></table></div>`; }
function renderVersions(){ $("#versions").innerHTML=`<div class="section-head"><div><p class="eyebrow">Course Versions</p><h2>Version Builder</h2></div>${versionSelector()}</div><div class="version-grid">${VERSIONS.map(v=>{const m=metrics(v), meta=VERSION_META[v]; return `<article class="panel version-panel"><h3>${esc(v)}</h3><dl><dt>Canvas course ID</dt><dd>${esc(targetCourseId(v)||"Not set")}</dd><dt>Delivery mode</dt><dd>${esc(meta.mode)}</dd><dt>Branding rules</dt><dd>${esc(meta.brand)}</dd><dt>Policy rules</dt><dd>${esc(meta.policy)}</dd><dt>Items included</dt><dd>${m.total}</dd><dt>Items excluded</dt><dd>${data.content.length-m.total}</dd><dt>Sync status</dt><dd>${badge(m.out?"Out of Sync":"Synced")}</dd></dl><div class="row-actions horizontal">${["Create Version Plan","Preview Version","Generate Customizations","Approve Version","Send Version to Canvas","Mark Version Complete"].map(x=>`<button data-version-action="${x}" data-version="${v}">${x}</button>`).join("")}</div></article>`}).join("")}</div>`; }
function renderAssignments(){ $("#assignments").innerHTML=`<div class="section-head"><div><p class="eyebrow">Major Assignments</p><h2>Master-approved signature assessments</h2></div>${versionSelector()}</div><div class="assignment-grid">${data.majorAssignments.map(a=>`<article class="panel assignment"><h3>${esc(a.title)}</h3>${["purpose","instructions","deliverables","rubric","sloMapping","genEdMapping","canvasSettings"].map(k=>`<h4>${label(k)}</h4><p>${esc(a[k])}</p>`).join("")}</article>`).join("")}</div>`; }
function exportPreview(r){ return `<h2>Canvas Export Preview</h2><dl class="preview-dl"><dt>Target Canvas course ID</dt><dd>${esc(r.canvasTargetCourseId||targetCourseId())}</dd><dt>Module name</dt><dd>Week ${esc(r.week)}: ${esc(r.module)}</dd><dt>Content type</dt><dd>${esc(r.contentType)}</dd><dt>Title</dt><dd>${esc(r.title)}</dd><dt>Body/content</dt><dd>${r.aiDraft||`<p>${esc(r.curriculum)}</p>`}</dd><dt>Assignment points</dt><dd>${esc(r.points||"N/A")}</dd><dt>Discussion settings</dt><dd>${esc(r.contentType==="Discussion"?"Prompt plus replies requirement":"N/A")}</dd><dt>Publish status</dt><dd>${esc(r.publishStatus)}</dd><dt>Included SLOs</dt><dd>${esc(r.slos)}</dd><dt>Gen Ed outcomes</dt><dd>${esc(r.genEdOutcomes)}</dd><dt>Customization notes</dt><dd>${esc(r.customizationNotes||"None")}</dd></dl>`; }
function renderPreview(){ const ready=rowsFor().filter(r=>r.facultyStatus==="Approved"); $("#preview").innerHTML=`<div class="section-head"><div><p class="eyebrow">Canvas Export</p><h2>Preview before sending</h2></div>${versionSelector()}</div><div class="panel"><button data-export-scope="item">Send only selected item</button> <button data-export-scope="module">Send selected module</button> <button data-export-scope="version">Send entire selected course version</button></div>${ready.map(r=>`<article class="panel preview"><h3>${esc(r.title)}</h3>${exportPreview(r)}<button data-action="send" data-id="${r.id}">Send approved item to Canvas</button></article>`).join("")||`<div class="panel">No approved items are ready for ${esc(workingVersion)}.</div>`}`; }
function renderSettings(){ $("#settings").innerHTML=`<div class="section-head"><div><p class="eyebrow">Settings</p><h2>Local browser settings only</h2><p>Never enter Gemini API keys or Canvas tokens here.</p></div></div><form id="settingsForm" class="panel form">${[["appsScriptUrl","Google Apps Script Web App URL"],["sheetId","Google Sheet ID"],["canvasBaseUrl","Default Canvas Base URL"],["masterShellCourseId","Master Shell Canvas Course ID"],["inPersonCourseId","In-Person Canvas Course ID"],["onlineHybridCourseId","Online/Hybrid Canvas Course ID"],["weLeadCsCourseId","WE Lead CS Canvas Course ID"]].map(([n,l])=>`<label>${l}<input name="${n}" value="${esc(settings[n]||"")}"></label>`).join("")}<button class="gold">Save settings to localStorage</button></form><div class="panel warning"><strong>Security note:</strong> Store GEMINI_API_KEY, CANVAS_API_TOKEN, and DEFAULT_CANVAS_BASE_URL only in Apps Script PropertiesService.</div>`; }
function render(){ renderDashboard(); renderTable(); renderVersions(); renderAssignments(); renderPreview(); renderSettings(); }
function fallbackVersionDraft(r){ const meta=VERSION_META[workingVersion]; return `<h2>${esc(r.title)} (${esc(workingVersion)})</h2><p><strong>Customization prompt:</strong> ${esc(meta.prompt)}</p><p>${esc(r.curriculum)}</p><h3>Version notes</h3><ul><li>${esc(meta.brand)}</li><li>${esc(meta.policy)}</li></ul>`; }
async function workflow(action,id){ const row=data.content.find(r=>r.id===id); if(!row) return; try{ if(action==="view") return openModal(`<h2>${esc(row.title)}</h2>${row.aiDraft||"<p>No draft yet.</p>"}`); if(action==="preview-export") return openModal(exportPreview(row)); if(action==="version-customize"){ const res=await api("generateVersionCustomization",{row,version:workingVersion,prompt:VERSION_META[workingVersion].prompt}).catch(()=>({html:fallbackVersionDraft(row)})); row.aiDraft=res.html||res.draftHtml||fallbackVersionDraft(row); row.customizationNotes=`Customized for ${workingVersion}`; row.versionSyncStatus="Customized Draft"; row.publishStatus="Draft"; toast("Version customization generated."); }
    if(action==="approve-version"){ row.facultyStatus="Approved"; row.publishStatus="Approved"; row.versionSyncStatus="Version Approved"; await api("approveVersionItem",{row,version:workingVersion}).catch(()=>null); toast("Version item approved."); }
    if(action==="out-sync"){ row.versionSyncStatus="Out of Sync"; await api("markOutOfSync",{row,version:workingVersion}).catch(()=>null); toast("Item marked out of sync.","warn"); }
    if(action==="send"){ const courseId=row.canvasTargetCourseId||targetCourseId(); if(row.facultyStatus!=="Approved") throw new Error("Faculty Status must be Approved before sending to Canvas."); if(!includesVersion(row)) throw new Error("Include in Version must match the selected working version."); if(!courseId) throw new Error("Canvas Target Course ID is required."); if(!["Ready","Approved"].includes(row.publishStatus)) throw new Error("Publish Status must be Ready or Approved."); const res=await api("sendVersionItemToCanvas",{row,version:workingVersion,canvasCourseId:courseId}); row.canvasExportStatus="Sent"; row.canvasStatus="Sent"; row.canvasExportDate=today(); row.canvasItemUrl=res.canvasUrl||row.canvasItemUrl; toast("Approved version content sent to Canvas."); }
    save(); render(); } catch(e){ toast(e.message,"bad"); } }
function openModal(html){ $("#modalContent").innerHTML=html; $("#modal").classList.add("open"); }
document.addEventListener("click", async e=>{ const tab=e.target.closest("[data-tab]"); if(tab){ document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===tab.dataset.tab)); document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===tab)); } const a=e.target.closest("[data-action]"); if(a) workflow(a.dataset.action,a.dataset.id); if(e.target.id==="loadSampleBtn"){ data=normalizeData(structuredClone(window.INF125_SAMPLE_DATA)); save(); render(); toast("Sample version data loaded."); } if(e.target.id==="syncBtn"){ try{ const res=await api("getVersionData",{version:workingVersion}); data=normalizeData({...data,...res}); save(); render(); toast("Version data loaded from Apps Script."); }catch(err){ toast(err.message,"bad"); } } const va=e.target.closest("[data-version-action]"); if(va){ const v=va.dataset.version, act=va.dataset.versionAction; try{ await api(act==="Send Version to Canvas"?"sendEntireVersionToCanvas":"createVersionPlan",{version:v,rows:rowsFor(v),canvasCourseId:targetCourseId(v)}).catch(()=>null); if(act==="Generate Customizations") rowsFor(v).forEach(r=>{r.aiDraft ||= fallbackVersionDraft(r); r.versionSyncStatus="Customized Draft";}); if(act==="Approve Version") rowsFor(v).forEach(r=>{r.facultyStatus="Approved"; r.publishStatus="Approved"; r.versionSyncStatus="Version Approved";}); if(act==="Mark Version Complete") rowsFor(v).forEach(r=>r.versionSyncStatus="Complete"); save(); render(); toast(`${act} completed for ${v}.`); }catch(err){toast(err.message,"bad");}} });
document.addEventListener("change", e=>{ if(e.target.id==="workingVersion"){ workingVersion=e.target.value; saveSettings(); render(); }});
$("#closeModal").onclick=()=>$("#modal").classList.remove("open");
document.addEventListener("submit", e=>{ if(e.target.id==="settingsForm"){ e.preventDefault(); settings={...settings,...Object.fromEntries(new FormData(e.target).entries())}; saveSettings(); render(); toast("Settings saved locally."); }});
render();
