const STORE_KEY="coursebuild.pilot.v4";
const SETTINGS_KEY="coursebuild.settings.v1";
const clone=v=>JSON.parse(JSON.stringify(v));
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
let data=JSON.parse(localStorage.getItem(STORE_KEY)||"null")||clone(window.COURSEBUILD_SAMPLE);
let settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}");
let selectedItemId=data.items?.[0]?.id||null;
data.source ||= {text:"",digest:"",fileName:"",importedAt:"",importMode:"sample"};
data.architecture ||= {status:"Draft",approvedAt:"",approvedBy:"Instructor"};
normalizeKeys();
function normalizeKeys(){(data.items||[]).forEach(i=>i.coursebuildKey ||= `coursebuild:${data.profile?.id||"course"}:${i.id}`);}
function save(){normalizeKeys();localStorage.setItem(STORE_KEY,JSON.stringify(data));}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
function toast(m){const e=$("#toast");e.textContent=m;e.className="show";setTimeout(()=>e.className="",2800);}
function statusClass(s){s=String(s).toLowerCase();if(/approved|ready|sent|current|pass/.test(s))return"good";if(/review|draft|custom|warning|needs/.test(s))return"warn";return"muted";}
function badge(s){return `<span class="badge ${statusClass(s)}">${esc(s)}</span>`;}
function moduleFor(i){return data.modules.find(m=>m.id===i.moduleId);}
function invalidateArchitecture(){data.architecture={status:"Draft",approvedAt:"",approvedBy:"Instructor"};(data.items||[]).forEach(i=>{if(i.status==="Approved")i.status="Needs Review";});}
async function api(action,payload={}){if(!settings.appsScriptUrl)throw new Error("Add the Apps Script Web App URL in Settings first.");const r=await fetch(settings.appsScriptUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,course:data.profile,canvasCourseId:settings.canvasCourseId,canvasBaseUrl:settings.canvasBaseUrl,architectureApproved:data.architecture.status==="Approved",...payload})});const j=await r.json().catch(()=>({ok:false,error:"Backend did not return JSON."}));if(!r.ok||j.ok===false)throw new Error(j.error||"CourseBuild request failed.");return j.data||j;}
function renderProfile(){$("#profile").innerHTML=`<div class="section-head"><div><p class="eyebrow">Course Profile</p><h2>${esc(data.profile.code||"New course")} · ${esc(data.profile.title||"Untitled")}</h2><p>Define the reusable course context that grounds planning and generation.</p></div>${badge("Configured")}</div><form id="profileForm" class="panel form"><div class="grid two"><label>Course code<input name="code" value="${esc(data.profile.code||"")}"></label><label>Course title<input name="title" value="${esc(data.profile.title||"")}"></label><label>Institution<input name="institution" value="${esc(data.profile.institution||"")}"></label><label>Audience<input name="audience" value="${esc(data.profile.audience||"")}"></label><label>Credits<input name="credits" value="${esc(data.profile.credits||"")}"></label><label>Delivery mode<select name="defaultDeliveryMode"><option>In-Person</option><option>Online</option><option>Hybrid</option><option>Flexible</option></select></label></div><label>Description<textarea name="description" rows="4">${esc(data.profile.description||"")}</textarea></label><label>Learning outcomes<textarea name="outcomes" rows="6">${esc((data.profile.outcomes||[]).join("\n"))}</textarea></label><label>Generation guardrails<textarea name="policies" rows="4">${esc((data.profile.policies||[]).join("\n"))}</textarea></label><button class="primary">Save course profile</button></form>`;const s=$("#profileForm select");if(s)s.value=data.profile.defaultDeliveryMode||"In-Person";$("#profileForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);data.profile={...data.profile,...Object.fromEntries(f.entries()),outcomes:String(f.get("outcomes")||"").split(/\n+/).map(x=>x.trim()).filter(Boolean),policies:String(f.get("policies")||"").split(/\n+/).map(x=>x.trim()).filter(Boolean)};invalidateArchitecture();save();renderAll();toast("Course profile saved. Architecture approval reset.");};}
function architectureEditor(){return data.modules.map((m,idx)=>`<article class="panel module editor-module" data-module="${m.id}"><div class="module-edit-head"><span class="module-number">${idx+1}</span><input class="module-title" data-module-title="${m.id}" value="${esc(m.title)}"><div class="row-actions"><button data-move-module="up" data-id="${m.id}" ${idx===0?"disabled":""}>↑</button><button data-move-module="down" data-id="${m.id}" ${idx===data.modules.length-1?"disabled":""}>↓</button><button data-delete-module="${m.id}">Delete</button></div></div><textarea class="module-summary" data-module-summary="${m.id}" rows="2">${esc(m.summary||"")}</textarea><div class="item-editor-list">${data.items.filter(i=>i.moduleId===m.id).map(i=>itemEditor(i)).join("")||"<p class='muted-text'>No LMS items yet.</p>"}</div><button data-add-item="${m.id}">+ Add LMS item</button></article>`).join("");}
function itemEditor(i){return `<div class="item-edit" data-item-edit="${i.id}"><select data-item-type="${i.id}"><option>Page</option><option>Assignment</option><option>Discussion</option></select><input data-item-title="${i.id}" value="${esc(i.title)}" placeholder="Item title"><input data-item-purpose="${i.id}" value="${esc(i.purpose||"")}" placeholder="Purpose"><input data-item-points="${i.id}" type="number" min="0" value="${Number(i.points||0)}"><button data-delete-item="${i.id}">Delete</button></div>`;}
function renderPlan(){const a=data.architecture.status||"Draft";$("#plan").innerHTML=`<div class="section-head"><div><p class="eyebrow">Import + Architecture</p><h2>Shape the LMS blueprint before content generation.</h2><p>Import source material, generate a proposal, edit it, then explicitly approve the architecture.</p></div>${badge(a)}</div><div class="grid two"><article class="panel"><h3>1. Import course source</h3><input id="sourceFile" type="file" accept=".txt,.md,.csv,.html,.htm,application/pdf"><textarea id="sourceText" class="source-input" rows="11" placeholder="Paste your syllabus or course plan…">${esc(data.source.text||"")}</textarea><div class="actions"><button id="saveSource">Save source</button><button id="architectBtn" class="primary">Generate architecture</button></div><p class="hint">${data.source.fileName?`File: ${esc(data.source.fileName)} · `:""}${data.source.digest?"Grounded source digest ready":data.source.text?`${data.source.text.length.toLocaleString()} characters retained`:"No source imported yet"}</p></article><article class="panel"><h3>2. Architecture approval</h3><p>Editing a module or LMS item automatically resets architecture approval.</p><div class="cards mini-cards"><article class="card"><span>Modules</span><strong>${data.modules.length}</strong></article><article class="card"><span>Items</span><strong>${data.items.length}</strong></article><article class="card"><span>Status</span><strong class="status-word">${esc(a)}</strong></article></div><div class="actions"><button id="addModule">+ Add module</button><button id="approveArchitecture" class="primary" ${!data.modules.length||!data.items.length?"disabled":""}>Approve architecture</button></div>${data.architecture.approvedAt?`<p class="hint">Approved ${esc(new Date(data.architecture.approvedAt).toLocaleString())}</p>`:""}</article></div><div class="architecture-toolbar"><h3>3. Edit proposed structure</h3><p>Rename or reorder modules, add/remove items, change item types, purposes, and points.</p></div><div class="architecture-list">${architectureEditor()}</div>`;
const f=$("#sourceFile");f.onchange=()=>handleFile(f.files?.[0]);$("#saveSource").onclick=()=>{data.source={...data.source,text:$("#sourceText").value.trim(),importedAt:new Date().toISOString(),importMode:"paste"};invalidateArchitecture();save();renderPlan();toast("Source saved.");};$("#architectBtn").onclick=generateArchitecture;$("#addModule").onclick=addModule;$("#approveArchitecture").onclick=approveArchitecture;bindArchitectureEditor();}
function bindArchitectureEditor(){document.querySelectorAll("[data-item-type]").forEach(s=>{const i=data.items.find(x=>x.id===s.dataset.itemType);if(i)s.value=i.type;s.onchange=()=>patchItem(i.id,{type:s.value});});document.querySelectorAll("[data-item-title]").forEach(e=>e.onchange=()=>patchItem(e.dataset.itemTitle,{title:e.value.trim()}));document.querySelectorAll("[data-item-purpose]").forEach(e=>e.onchange=()=>patchItem(e.dataset.itemPurpose,{purpose:e.value.trim()}));document.querySelectorAll("[data-item-points]").forEach(e=>e.onchange=()=>patchItem(e.dataset.itemPoints,{points:Number(e.value||0)}));document.querySelectorAll("[data-module-title]").forEach(e=>e.onchange=()=>patchModule(e.dataset.moduleTitle,{title:e.value.trim()}));document.querySelectorAll("[data-module-summary]").forEach(e=>e.onchange=()=>patchModule(e.dataset.moduleSummary,{summary:e.value.trim()}));document.querySelectorAll("[data-add-item]").forEach(b=>b.onclick=()=>addItem(b.dataset.addItem));document.querySelectorAll("[data-delete-item]").forEach(b=>b.onclick=()=>deleteItem(b.dataset.deleteItem));document.querySelectorAll("[data-delete-module]").forEach(b=>b.onclick=()=>deleteModule(b.dataset.deleteModule));document.querySelectorAll("[data-move-module]").forEach(b=>b.onclick=()=>moveModule(b.dataset.id,b.dataset.moveModule));}
function patchItem(id,p){const i=data.items.find(x=>x.id===id);if(!i)return;Object.assign(i,p);i.status="Planned";i.draftHtml="";invalidateArchitecture();save();renderPlan();}
function patchModule(id,p){const m=data.modules.find(x=>x.id===id);if(!m)return;Object.assign(m,p);invalidateArchitecture();save();renderPlan();}
function addModule(){const id=uid("m");data.modules.push({id,order:data.modules.length+1,title:`Module ${data.modules.length+1}`,summary:"",status:"Planned"});invalidateArchitecture();save();renderPlan();}
function addItem(moduleId){const id=uid("i");data.items.push({id,moduleId,type:"Page",title:"New LMS item",purpose:"",points:0,status:"Planned",draftHtml:"",coursebuildKey:`coursebuild:${data.profile?.id||"course"}:${id}`});selectedItemId=id;invalidateArchitecture();save();renderPlan();}
function deleteItem(id){data.items=data.items.filter(i=>i.id!==id);if(selectedItemId===id)selectedItemId=data.items[0]?.id||null;invalidateArchitecture();save();renderPlan();}
function deleteModule(id){data.modules=data.modules.filter(m=>m.id!==id);data.items=data.items.filter(i=>i.moduleId!==id);data.modules.forEach((m,i)=>m.order=i+1);invalidateArchitecture();save();renderPlan();}
function moveModule(id,dir){const idx=data.modules.findIndex(m=>m.id===id),to=dir==="up"?idx-1:idx+1;if(idx<0||to<0||to>=data.modules.length)return;[data.modules[idx],data.modules[to]]=[data.modules[to],data.modules[idx]];data.modules.forEach((m,i)=>m.order=i+1);invalidateArchitecture();save();renderPlan();}
function approveArchitecture(){if(!data.modules.length||!data.items.length)return toast("Add at least one module and LMS item first.");if(data.items.some(i=>!i.title||!i.purpose||!moduleFor(i)))return toast("Every LMS item needs a title, purpose, and module.");data.architecture={status:"Approved",approvedAt:new Date().toISOString(),approvedBy:"Instructor"};save();renderAll();toast("Architecture approved.");}
async function handleFile(file){if(!file)return;data.source.fileName=file.name;data.source.importedAt=new Date().toISOString();if(file.type==="application/pdf"||/\.pdf$/i.test(file.name)){try{const b64=await fileToBase64(file);const out=await api("importPdfArchitecture",{base64:b64,mimeType:"application/pdf",fileName:file.name});applyArchitecture(out,"PDF + AI");data.source.text="";data.source.digest=out.sourceDigest||"";data.source.importMode="PDF";save();renderAll();showView("plan");toast("PDF imported and architecture proposed.");}catch(e){toast(e.message);}}else{const text=await file.text();data.source.text=text;data.source.digest="";data.source.importMode="file";$("#sourceText").value=text;invalidateArchitecture();save();renderPlan();toast("File imported. Generate the architecture when ready.");}}
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]||"");r.onerror=reject;r.readAsDataURL(file);});}
function localArchitecture(text){const lines=text.split(/\n+/).map(s=>s.trim()).filter(Boolean);const seeds=lines.filter(l=>/^(week|module|unit)\s*\d+/i.test(l)).slice(0,12);const titles=(seeds.length?seeds:lines.filter(l=>l.length>6&&l.length<90&&!/[.!?]$/.test(l)).slice(0,6));const base=titles.length?titles:["Foundations","Core Concepts","Applied Practice","Integration"];const modules=base.map((t,i)=>({id:uid("m"),order:i+1,title:t.replace(/^(week|module|unit)\s*\d+\s*[:.-]?\s*/i,"")||`Module ${i+1}`,summary:"Planned from imported source. Review before approval.",status:"Planned"}));const items=[];modules.forEach((m,i)=>{items.push({id:uid("i"),moduleId:m.id,type:"Page",title:`${m.title}: Overview`,purpose:"Introduce the module focus and completion path.",points:0,status:"Planned",draftHtml:""});items.push({id:uid("i"),moduleId:m.id,type:i%2?"Assignment":"Discussion",title:i%2?`${m.title}: Applied Work`:`${m.title}: Discussion`,purpose:"Give learners a meaningful opportunity to apply or discuss the module focus.",points:i%2?20:0,status:"Planned",draftHtml:""});});return{modules,items,sourceDigest:text.slice(0,12000)};}
async function generateArchitecture(){const text=$("#sourceText").value.trim();if(text.length<80)return toast("Paste more source material first.");data.source.text=text;let a;try{a=await api("generateCourseArchitecture",{sourceText:text});data.source.importMode="AI architecture";}catch(e){a=localArchitecture(text);data.source.importMode="local fallback";}applyArchitecture(a,data.source.importMode);data.source.digest=a.sourceDigest||text.slice(0,12000);save();renderAll();showView("plan");toast(`Architecture proposed: ${data.modules.length} modules, ${data.items.length} items.`);}
function applyArchitecture(a,mode){data.modules=(a.modules||[]).map((m,i)=>({...m,id:m.id||uid("m"),order:i+1,status:"Planned"}));const byOrder=new Map(data.modules.map((m,i)=>[i+1,m.id]));data.items=(a.items||[]).map(i=>{const id=i.id||uid("i");return{...i,id,moduleId:i.moduleId||byOrder.get(Number(i.moduleOrder)||1)||data.modules[0]?.id,status:"Planned",draftHtml:"",coursebuildKey:`coursebuild:${data.profile?.id||"course"}:${id}`};});data.architecture={status:"Draft",approvedAt:"",approvedBy:"Instructor"};selectedItemId=data.items[0]?.id||null;data.source.importMode=mode;}
function renderReview(){if(data.architecture.status!=="Approved"){$("#review").innerHTML=`<div class="panel blocked"><h3>Approve the course architecture first.</h3><p>Content generation stays locked until the module and LMS-object structure is explicitly approved.</p><button data-go-plan class="primary">Review architecture</button></div>`;$("[data-go-plan]").onclick=()=>showView("plan");return;}const item=data.items.find(i=>i.id===selectedItemId)||data.items[0];if(!item){$("#review").innerHTML="<div class='panel'>No items yet.</div>";return;}selectedItemId=item.id;const m=moduleFor(item);$("#review").innerHTML=`<div class="section-head"><div><p class="eyebrow">Human Review Gate</p><h2>${esc(item.title)}</h2><p>${esc(m?.title||"")} · ${esc(item.type)}</p></div>${badge(item.status)}</div><div class="grid two"><article class="panel"><h3>Intent</h3><p>${esc(item.purpose||"")}</p>${item.points?`<p><strong>${item.points} points</strong></p>`:""}<div class="actions"><button id="generateBtn" class="primary">Generate draft</button><button id="approveBtn">Approve item</button></div></article><article class="panel"><h3>Draft</h3><div class="draft">${item.draftHtml||"<p class='muted-text'>No draft generated yet.</p>"}</div></article></div><article class="panel"><h3>Queue</h3><div class="item-list">${data.items.map(i=>`<button class="item-row" data-select-item="${i.id}"><span>${esc(i.type)} · ${esc(i.title)}</span>${badge(i.status)}</button>`).join("")}</div></article>`;$("#generateBtn").onclick=()=>generateItem(item.id);$("#approveBtn").onclick=()=>approveItem(item.id);document.querySelectorAll("[data-select-item]").forEach(b=>b.onclick=()=>{selectedItemId=b.dataset.selectItem;renderReview();});}
async function generateItem(id){if(data.architecture.status!=="Approved")return toast("Approve the architecture first.");const i=data.items.find(x=>x.id===id);if(!i)return;try{const out=await api("generateItem",{item:i,module:moduleFor(i),outcomes:data.profile.outcomes||[],sourceText:data.source.digest||data.source.text||""});i.draftHtml=out.draftHtml||out.html||"";i.status="Needs Review";}catch(e){i.draftHtml=`<h3>${esc(i.title)}</h3><p>${esc(i.purpose)}</p><p><strong>Pilot sample:</strong> Connect the secure backend for source-grounded generation.</p>`;i.status="Needs Review";}save();renderAll();showView("review");toast("Draft ready for review.");}
function approveItem(id){const i=data.items.find(x=>x.id===id);if(!i?.draftHtml)return toast("Generate a draft first.");i.status="Approved";save();renderAll();showView("review");toast("Item approved.");}
function readinessChecks(){return[{label:"Course title and description",pass:Boolean(data.profile.title&&data.profile.description)},{label:"Learning outcomes",pass:Boolean((data.profile.outcomes||[]).length)},{label:"Source retained or digested",pass:Boolean(data.source.text||data.source.digest)},{label:"Architecture exists",pass:Boolean(data.modules.length&&data.items.length)},{label:"Architecture explicitly approved",pass:data.architecture.status==="Approved"},{label:"Every item belongs to a module",pass:data.items.length>0&&data.items.every(i=>moduleFor(i))},{label:"Every item has a purpose",pass:data.items.length>0&&data.items.every(i=>String(i.purpose||"").trim())},{label:"All content items approved or sent",pass:data.items.length>0&&data.items.every(i=>["Approved","Sent"].includes(i.status))},{label:"Canvas connection configured",pass:Boolean(settings.canvasBaseUrl&&settings.canvasCourseId&&settings.appsScriptUrl)}];}
function renderBuild(){const c=readinessChecks(),passed=c.filter(x=>x.pass).length,approved=data.items.filter(i=>["Approved","Sent"].includes(i.status)).length;$("#build").innerHTML=`<div class="section-head"><div><p class="eyebrow">Readiness + Build</p><h2>Know what is ready before Canvas changes.</h2></div>${badge(c.every(x=>x.pass)?"Ready to build":"Not ready")}</div><div class="cards"><article class="card"><span>Checks</span><strong>${passed}/${c.length}</strong></article><article class="card"><span>Approved items</span><strong>${approved}/${data.items.length}</strong></article><article class="card"><span>Architecture</span><strong class="status-word">${esc(data.architecture.status)}</strong></article></div><article class="panel"><h3>Readiness audit</h3><div class="check-list">${c.map(x=>`<div class="check-row"><span class="check-icon">${x.pass?"✓":"!"}</span><span>${esc(x.label)}</span>${badge(x.pass?"Pass":"Needs attention")}</div>`).join("")}</div></article><article class="panel"><h3>Canvas build preview</h3>${data.modules.map(m=>`<div class="build-module"><b>${esc(m.title)}</b>${data.items.filter(i=>i.moduleId===m.id).map(i=>`<div class="build-row"><span>${esc(i.type)} · ${esc(i.title)}</span>${badge(i.status)}</div>`).join("")}</div>`).join("")}<div class="actions"><button id="sendApproved" class="primary" ${data.architecture.status!=="Approved"||approved===0?"disabled":""}>Send approved items to Canvas</button></div></article>`;$("#sendApproved").onclick=sendApproved;}
async function sendApproved(){if(data.architecture.status!=="Approved")return toast("Approve the architecture first.");for(const i of data.items.filter(x=>x.status==="Approved")){try{const out=await api("publishItem",{item:i,module:moduleFor(i)});i.status="Sent";i.canvasId=out.canvasId;i.canvasUrl=out.canvasUrl||"";}catch(e){toast(e.message);break;}}save();renderAll();}
function renderVersions(){$("#versions").innerHTML=`<div class="section-head"><div><p class="eyebrow">Versions</p><h2>Build once. Adapt without starting over.</h2><p>Version generation remains the next product slice.</p></div></div><div class="grid two">${(data.versions||[]).map(v=>`<article class="panel"><h3>${esc(v.name)}</h3><dl><dt>Mode</dt><dd>${esc(v.mode)}</dd><dt>Sync</dt><dd>${badge(v.syncStatus)}</dd></dl></article>`).join("")}</div>`;}
function renderSettings(){$("#settings").innerHTML=`<div class="section-head"><div><p class="eyebrow">Pilot Settings</p><h2>Connect the secure backend</h2></div></div><form id="settingsForm" class="panel form"><label>Apps Script Web App URL<input name="appsScriptUrl" value="${esc(settings.appsScriptUrl||"")}"></label><label>Canvas Base URL<input name="canvasBaseUrl" value="${esc(settings.canvasBaseUrl||"")}"></label><label>Canvas Course ID<input name="canvasCourseId" value="${esc(settings.canvasCourseId||"")}"></label><button class="primary">Save pilot settings</button></form>`;$("#settingsForm").onsubmit=e=>{e.preventDefault();settings=Object.fromEntries(new FormData(e.currentTarget).entries());saveSettings();renderAll();toast("Settings saved.");};}
function renderAll(){renderProfile();renderPlan();renderReview();renderBuild();renderVersions();renderSettings();}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("hidden",v.id!==id));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===id));}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("#closeModal").onclick=()=>$("#modal").close();renderAll();