/* CourseBuild v0.10 · local pilot cohort analysis */
(function(){
  const SCHEMA="coursebuild-pilot-evidence-v1";
  let reports=[];
  const stop=new Set(["the","and","for","that","with","this","was","were","from","have","has","had","but","not","too","very","into","out","our","your","you","use","using","coursebuild","course","canvas","would","could","more","most","some","any","its","it's","they","their","them","then","than","when","what","which","who","how","all","just","still","need","needed"]);
  const n=v=>Number(v||0);
  const pct=(a,b)=>b?Math.round(a/b*100):0;
  const mean=a=>a.length?a.reduce((s,v)=>s+n(v),0)/a.length:0;
  const median=a=>{const s=a.map(n).filter(Number.isFinite).sort((x,y)=>x-y);if(!s.length)return 0;const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;};
  const fmt=v=>Number(v||0).toFixed(1);
  function valid(r){return r&&r.schema===SCHEMA&&r.pilot&&r.pilot.feedback&&r.pilot.baseline;}
  function feedback(k){return reports.map(r=>n(r.pilot.feedback[k])).filter(v=>v>0);}
  function yesRate(k){const vals=reports.map(r=>String(r.pilot.feedback[k]||"").toLowerCase()).filter(Boolean);return{yes:vals.filter(v=>v==="yes").length,total:vals.length};}
  function telemetrySummary(r){const e=r.telemetry||{};if(e.summary)return e.summary;const events=Array.isArray(e.events)?e.events:[];const durations=events.map(x=>n(x.durationMs)).filter(v=>v>0);return{measuredMinutes:durations.reduce((s,v)=>s+v,0)/60000,failures:events.filter(x=>x.type==="failure").length};}
  function manualMinutes(r){const b=r.pilot.baseline||{},items=n(r.course?.items),versions=(r.versions||[]).filter(v=>v.approvalStatus==="Approved").length;return n(b.architectureMinutes)+items*(n(b.contentMinutes)+n(b.canvasMinutes))+items*versions*n(b.versionMinutes);}
  function savedMinutes(r){const t=telemetrySummary(r);const measured=n(t.measuredMinutes||t.measuredWorkflowMinutes);return Math.max(0,manualMinutes(r)-measured);}
  function tokenize(field){const counts={};reports.forEach(r=>{String(r.pilot.feedback[field]||"").toLowerCase().match(/[a-z][a-z'-]{2,}/g)?.forEach(w=>{w=w.replace(/^'+|'+$/g,"");if(!stop.has(w)&&w.length>2)counts[w]=(counts[w]||0)+1;});});return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,8);}
  function groupBy(fn){const m={};reports.forEach(r=>{const k=fn(r)||"Unspecified";(m[k]||=[]).push(r);});return m;}
  function segmentRows(groups){return Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).map(([name,rs])=>{const ratings=rs.map(r=>n(r.pilot.feedback.usefulness)).filter(Boolean);const reuse=rs.map(r=>String(r.pilot.feedback.wouldUseAgain||"")).filter(Boolean);return `<tr><td>${esc(name)}</td><td>${rs.length}</td><td>${ratings.length?fmt(mean(ratings)):"—"}</td><td>${reuse.length?pct(reuse.filter(x=>x==="Yes").length,reuse.length)+"%":"—"}</td><td>${Math.round(median(rs.map(savedMinutes)))} min</td></tr>`;}).join("");}
  function summary(){const use=feedback("usefulness"),ease=feedback("ease"),control=feedback("control"),confidence=feedback("confidence"),again=yesRate("wouldUseAgain"),recommend=yesRate("wouldRecommend"),saved=reports.map(savedMinutes),failures=reports.reduce((s,r)=>s+n(telemetrySummary(r).failures),0),ready=(reports.flatMap(r=>r.versions||[]).filter(v=>v.reconciliation?.readyForInstructorReview)).length,totalRecon=reports.flatMap(r=>r.versions||[]).filter(v=>v.reconciliation).length;
    return{participants:reports.length,usefulness:mean(use),ease:mean(ease),control:mean(control),confidence:mean(confidence),again,recommend,medianSaved:median(saved),failures,ready,totalRecon};
  }
  function words(field,title){const rows=tokenize(field);return `<article class="panel"><h3>${esc(title)}</h3>${rows.length?`<div class="theme-list">${rows.map(([w,c])=>`<div><span>${esc(w)}</span><b>${c}</b></div>`).join("")}</div>`:`<p class="muted-text">No text responses imported yet.</p>`}</article>`;}
  function caseStudy(s){if(!reports.length)return "Import pilot evidence files to generate a cohort summary.";const again=s.again.total?`${pct(s.again.yes,s.again.total)}% said they would use CourseBuild again`:"reuse intent is not yet available";const rec=s.recommend.total?`${pct(s.recommend.yes,s.recommend.total)}% would recommend a pilot to a colleague`:"recommendation intent is not yet available";return `Across ${s.participants} completed or exported CourseBuild pilots, average usefulness was ${fmt(s.usefulness)}/5 and confidence was ${fmt(s.confidence)}/5. Median estimated manual time avoided was ${Math.round(s.medianSaved)} minutes per pilot, based on participant-supplied manual baselines and locally measured workflow/API time. ${again}; ${rec}. ${s.failures} failure event${s.failures===1?"":"s"} were recorded across the imported evidence. These findings are pilot evidence, not production performance claims.`;}
  function render(){const s=summary();$("#cohort").innerHTML=`<div class="section-head"><div><p class="eyebrow">Pilot Cohort</p><h2>Turn individual pilots into product evidence.</h2><p>Import multiple CourseBuild evidence exports. Analysis runs locally in this browser; files are not uploaded by this feature.</p></div>${badge(`${reports.length} valid pilot${reports.length===1?"":"s"}`)}</div>
    <article class="panel"><h3>Import evidence</h3><label class="file-drop">Select CourseBuild pilot JSON files<input id="cohortFiles" type="file" accept="application/json,.json" multiple></label><div id="cohortImportStatus" class="hint">Expected schema: ${SCHEMA}</div><div class="actions"><button id="clearCohort">Clear cohort</button><button id="exportCohort" ${!reports.length?"disabled":""}>Export aggregate JSON</button><button id="copyCaseStudy" class="primary" ${!reports.length?"disabled":""}>Copy case-study summary</button></div></article>
    <div class="cards cohort-cards"><article class="card"><span>Participants</span><strong>${s.participants}</strong></article><article class="card"><span>Avg usefulness</span><strong>${s.participants?fmt(s.usefulness):"—"}</strong></article><article class="card"><span>Avg confidence</span><strong>${s.participants?fmt(s.confidence):"—"}</strong></article><article class="card"><span>Median time avoided</span><strong>${s.participants?Math.round(s.medianSaved)+"m":"—"}</strong></article></div>
    <div class="grid two"><article class="panel"><h3>Adoption signals</h3><dl><dt>Use again — Yes</dt><dd>${s.again.total?pct(s.again.yes,s.again.total)+"%":"—"}</dd><dt>Recommend pilot — Yes</dt><dd>${s.recommend.total?pct(s.recommend.yes,s.recommend.total)+"%":"—"}</dd><dt>Avg ease</dt><dd>${s.participants?fmt(s.ease)+"/5":"—"}</dd><dt>Avg control</dt><dd>${s.participants?fmt(s.control)+"/5":"—"}</dd><dt>Recorded failures</dt><dd>${s.failures}</dd><dt>Reconciled shells ready</dt><dd>${s.totalRecon?`${s.ready}/${s.totalRecon}`:"—"}</dd></dl></article><article class="panel"><h3>Case-study-ready summary</h3><p id="caseStudySummary">${esc(caseStudy(s))}</p><p class="hint">Time avoided remains estimate-based until manual baselines are independently observed.</p></article></div>
    <div class="grid two">${words("friction","Common friction language")}${words("bestPart","Common value language")}</div>
    <article class="panel"><h3>Results by role</h3><div class="table-wrap"><table><thead><tr><th>Role</th><th>n</th><th>Usefulness</th><th>Use again</th><th>Median time avoided</th></tr></thead><tbody>${segmentRows(groupBy(r=>r.pilot.participant.role))}</tbody></table></div></article>
    <article class="panel"><h3>Results by Canvas experience</h3><div class="table-wrap"><table><thead><tr><th>Experience</th><th>n</th><th>Usefulness</th><th>Use again</th><th>Median time avoided</th></tr></thead><tbody>${segmentRows(groupBy(r=>r.pilot.participant.canvasExperience))}</tbody></table></div></article>`;
    $("#cohortFiles").onchange=importFiles;$("#clearCohort").onclick=()=>{reports=[];render();};$("#exportCohort").onclick=exportAggregate;$("#copyCaseStudy").onclick=async()=>{try{await navigator.clipboard.writeText(caseStudy(s));toast("Case-study summary copied.");}catch(e){toast("Copy unavailable in this browser.");}};
  }
  async function importFiles(e){const files=[...e.target.files];let invalid=0;const seen=new Set(reports.map(r=>r.pilot?.pilotId));for(const f of files){try{const r=JSON.parse(await f.text());if(!valid(r)){invalid++;continue;}const id=r.pilot?.pilotId||`${f.name}:${r.exportedAt||""}`;if(!seen.has(id)){reports.push(r);seen.add(id);}}catch(err){invalid++;}}render();const status=$("#cohortImportStatus");if(status)status.textContent=`Imported ${files.length-invalid} valid file(s)${invalid?`; ${invalid} rejected for invalid JSON/schema`:""}.`;window.CourseBuildTelemetry?.event?.("cohort_imported",{valid:files.length-invalid,invalid,total:reports.length});}
  function exportAggregate(){const s=summary();const out={schema:"coursebuild-pilot-cohort-v1",exportedAt:new Date().toISOString(),participantCount:reports.length,summary:{...s,caseStudy:caseStudy(s)},segments:{roles:Object.fromEntries(Object.entries(groupBy(r=>r.pilot.participant.role)).map(([k,v])=>[k,{n:v.length,avgUsefulness:mean(v.map(r=>n(r.pilot.feedback.usefulness)).filter(Boolean)),yesUseAgain:v.filter(r=>r.pilot.feedback.wouldUseAgain==="Yes").length,medianEstimatedSavedMinutes:median(v.map(savedMinutes))}])),canvasExperience:Object.fromEntries(Object.entries(groupBy(r=>r.pilot.participant.canvasExperience)).map(([k,v])=>[k,{n:v.length,avgUsefulness:mean(v.map(r=>n(r.pilot.feedback.usefulness)).filter(Boolean)),yesUseAgain:v.filter(r=>r.pilot.feedback.wouldUseAgain==="Yes").length,medianEstimatedSavedMinutes:median(v.map(savedMinutes))}]))},themes:{friction:tokenize("friction"),value:tokenize("bestPart")}};const blob=new Blob([JSON.stringify(out,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`coursebuild-cohort-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);window.CourseBuildTelemetry?.event?.("cohort_exported",{participants:reports.length});}
  window.renderCohort=render;render();
})();
