/* CourseBuild v0.13 · opt-in managed workspace sync */
(function(){
  const CONFIG_KEY='coursebuild.managed.config.v1';
  const REV_KEY='coursebuild.managed.revisions.v1';
  const TOKEN_MIN=32;
  const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f;}catch(e){return f;}};
  const writeJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const cfg=readJson(CONFIG_KEY,{enabled:false,url:'',workspaceToken:'',workspaceId:'',lastSyncAt:''});
  const revisions=readJson(REV_KEY,{});
  const now=()=>new Date().toISOString();
  function randomToken(){const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('');}
  async function call(action,payload={}){
    if(!cfg.url)throw new Error('Add the managed-storage Web App URL first.');
    if(String(cfg.workspaceToken||'').length<TOKEN_MIN)throw new Error('Create or paste a valid workspace key first.');
    const r=await fetch(cfg.url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,workspaceToken:cfg.workspaceToken,...payload})});
    const j=await r.json().catch(()=>({ok:false,error:'Managed storage did not return JSON.'}));if(!r.ok||j.ok===false)throw new Error(j.error||'Managed storage request failed.');return j.data||j;
  }
  function saveCfg(){writeJson(CONFIG_KEY,cfg);writeJson(REV_KEY,revisions);}
  function activeEnvelope(){return window.CourseBuildProjects?.snapshot?.();}
  async function ping(){const out=await call('managedPing');cfg.workspaceId=out.workspaceId||'';cfg.enabled=true;cfg.lastSyncAt=now();saveCfg();return out;}
  async function pushCurrent(){const env=activeEnvelope();if(!env)throw new Error('No active CourseBuild project is available.');const expected=Object.prototype.hasOwnProperty.call(revisions,env.id)?revisions[env.id]:0;const out=await call('saveManagedProject',{project:env,expectedRevision:expected});revisions[env.id]=out.revision;cfg.lastSyncAt=now();saveCfg();window.CourseBuildTelemetry?.event?.('managed_project_saved',{projectId:env.id,revision:out.revision});renderManaged();return out;}
  async function listRemote(){return(await call('listManagedProjects')).projects||[];}
  async function pullProject(id){const out=await call('loadManagedProject',{projectId:id}),env=out.project;if(!env)throw new Error('Managed project did not return a project envelope.');revisions[id]=out.revision||env.managedRevision||1;saveCfg();const localIds=new Set(window.CourseBuildProjects?.list?.().map(x=>x.id)||[]);if(localIds.has(env.id)){const current=window.CourseBuildProjects?.snapshot?.();if(current?.id===env.id&&JSON.stringify(current)!==JSON.stringify(env)){if(!confirm('This managed project has the same ID as a local project. Replace the local copy with the managed version?'))return;}}localStorage.setItem(`coursebuild.project.v1.${env.id}`,JSON.stringify(env));let idx=readJson('coursebuild.projects.v1',[]);const meta={id:env.id,name:env.name||'Untitled Course',createdAt:env.createdAt||now(),updatedAt:env.updatedAt||now(),courseCode:env.courseState?.profile?.code||'',courseTitle:env.courseState?.profile?.title||''};const pos=idx.findIndex(x=>x.id===env.id);if(pos>=0)idx[pos]=meta;else idx.push(meta);writeJson('coursebuild.projects.v1',idx);localStorage.setItem('coursebuild.projects.active.v1',env.id);localStorage.setItem('coursebuild.pilot.v4',JSON.stringify(env.courseState));if(env.telemetry)writeJson('coursebuild.telemetry.v1',env.telemetry);else localStorage.removeItem('coursebuild.telemetry.v1');if(env.externalPilot)writeJson('coursebuild.externalPilot.v1',env.externalPilot);else localStorage.removeItem('coursebuild.externalPilot.v1');window.CourseBuildTelemetry?.event?.('managed_project_loaded',{projectId:env.id,revision:revisions[id]});location.reload();}
  async function deleteRemote(id){if(!confirm('Delete this managed copy? This does not delete the local project.'))return;await call('deleteManagedProject',{projectId:id});delete revisions[id];saveCfg();window.CourseBuildTelemetry?.event?.('managed_project_deleted',{projectId:id});await refreshRemote();}
  async function refreshRemote(){const host=document.querySelector('#managedRemoteList');if(host)host.innerHTML='<p class="muted-text">Loading managed projects…</p>';try{const rows=await listRemote();if(host)host.innerHTML=rows.length?rows.map(x=>`<article class="managed-row"><div><b>${esc(x.name)}</b><span>${esc([x.courseCode,x.courseTitle].filter(Boolean).join(' · ')||'No course profile')}</span><small>Revision ${Number(x.revision||1)} · updated ${esc(x.updatedAt?new Date(x.updatedAt).toLocaleString():'Unknown')}</small></div><div class="actions"><button data-managed-load="${esc(x.id)}">Open managed</button><button data-managed-delete="${esc(x.id)}">Delete managed</button></div></article>`).join(''):'<p class="muted-text">No managed projects in this workspace yet.</p>';document.querySelectorAll('[data-managed-load]').forEach(b=>b.onclick=()=>pullProject(b.dataset.managedLoad));document.querySelectorAll('[data-managed-delete]').forEach(b=>b.onclick=()=>deleteRemote(b.dataset.managedDelete));}catch(e){if(host)host.innerHTML=`<p class="hint">${esc(e.message)}</p>`;}}
  function renderManaged(){const projects=document.querySelector('#projects');if(!projects)return;let host=document.querySelector('#managedWorkspace');if(!host){host=document.createElement('article');host.id='managedWorkspace';host.className='panel managed-workspace';projects.appendChild(host);}host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">Managed workspace · v0.13</p><h3>Reopen projects beyond this browser.</h3><p>Opt-in pilot sync using a separate Apps Script storage endpoint. The workspace key is a bearer secret, not production authentication.</p></div>${badge(cfg.enabled&&cfg.workspaceId?`Connected · ${cfg.workspaceId}`:'Local only')}</div><div class="grid two"><label>Managed storage Web App URL<input id="managedUrl" value="${esc(cfg.url||'')}" placeholder="https://script.google.com/macros/s/…/exec"></label><label>Workspace key<input id="managedToken" type="password" value="${esc(cfg.workspaceToken||'')}" placeholder="Generate or paste a workspace key"></label></div><div class="actions"><button id="generateManagedToken">Generate workspace key</button><button id="connectManaged">Test + connect</button><button id="pushManaged" class="primary" ${!cfg.enabled?'disabled':''}>Save current project to managed</button><button id="refreshManaged" ${!cfg.enabled?'disabled':''}>Refresh managed list</button></div><p class="hint">Keep the workspace key private. Anyone with the endpoint URL + key can access that workspace's managed project copies. Real user sign-in remains a later productization step.</p><div id="managedRemoteList"><p class="muted-text">${cfg.enabled?'Refresh to load managed projects.':'Connect a managed workspace to list server-side project copies.'}</p></div>`;
    const url=host.querySelector('#managedUrl'),token=host.querySelector('#managedToken');
    const stash=()=>{cfg.url=url.value.trim();cfg.workspaceToken=token.value.trim();cfg.enabled=false;cfg.workspaceId='';saveCfg();};url.onchange=stash;token.onchange=stash;
    host.querySelector('#generateManagedToken').onclick=()=>{token.value=randomToken();cfg.workspaceToken=token.value;cfg.enabled=false;cfg.workspaceId='';saveCfg();toast('Workspace key generated. Save it somewhere secure if you need cross-device access.');};
    host.querySelector('#connectManaged').onclick=async()=>{cfg.url=url.value.trim();cfg.workspaceToken=token.value.trim();saveCfg();try{const out=await ping();toast(`Managed workspace ${out.workspaceId} connected.`);renderManaged();await refreshRemote();}catch(e){cfg.enabled=false;saveCfg();toast(e.message);}};
    host.querySelector('#pushManaged').onclick=async()=>{try{const out=await pushCurrent();toast(`Managed copy saved at revision ${out.revision}.`);await refreshRemote();}catch(e){toast(e.message);}};
    host.querySelector('#refreshManaged').onclick=refreshRemote;
  }
  const originalProjectsRender=window.CourseBuildProjects?.render; if(originalProjectsRender){window.CourseBuildProjects.render=function(){originalProjectsRender();renderManaged();};}
  window.CourseBuildManaged={config:()=>({...cfg,workspaceToken:cfg.workspaceToken?'(set)':''}),ping,pushCurrent,listRemote,pullProject,render:renderManaged};
  renderManaged();
})();
