/* CourseBuild v0.9 · guided external pilot */
(function(){
  const PILOT_KEY="coursebuild.externalPilot.v1";
  const DEFAULT_TASKS=[
    {id:"baseline",title:"Capture the manual baseline",help:"Estimate how long this course would normally take to architect, draft, assemble in Canvas, and adapt for another delivery mode."},
    {id:"source",title:"Import a real course source",help:"Use a syllabus or course plan from a course you are comfortable testing."},
    {id:"architecture",title:"Review and approve the architecture",help:"Edit the proposed modules/LMS items until they reflect your intent, then approve the architecture."},
    {id:"content",title:"Generate and approve content",help:"Generate at least three LMS objects, review them, and approve only what you would actually use."},
    {id:"canvas",title:"Build or preview Canvas",help:"If you have a sandbox, build approved items. Otherwise complete the readiness and preview steps."},
    {id:"version",title:"Try one delivery version",help:"Generate and review one Online, In-Person, or Accelerated variant."},
    {id:"feedback",title:"Complete the pilot reflection",help:"Rate usefulness, confidence, control, and willingness to use CourseBuild again."}
  ];
  function fresh(){return{pilotId:`pilot-${Date.now().toString(36)}`,participant:{name:"",role:"Faculty",institution:"",discipline:"",canvasExperience:"Intermediate"},consent:{acknowledged:false,completedAt:""},baseline:{architectureMinutes:0,contentMinutes:0,canvasMinutes:0,versionMinutes:0,notes:""},tasks:DEFAULT_TASKS.map(t=>({...t,status:"Not started",startedAt:"",completedAt:""})),feedback:{usefulness:0,ease:0,control:0,confidence:0,wouldUseAgain:"",wouldRecommend:"",bestPart:"",friction:"",missing:"",notes:""},startedAt:new Date().toISOString(),completedAt:""};}
  let pilot=JSON.parse(localStorage.getItem(PILOT_KEY)||"null")||fresh();
  function persist(){localStorage.setItem(PILOT_KEY,JSON.stringify(pilot));}
  function task(id){return pilot.tasks.find(t=>t.id===id);}
  function setTask(id,status){const t=task(id);if(!t)return;if(status==="In progress"&&!t.startedAt)t.startedAt=new Date().toISOString();if(status==="Complete")t.completedAt=new Date().toISOString();t.status=status;persist();renderPilot();window.CourseBuildTelemetry?.event?.("pilot_task",{taskId:id,status});}
  function completed(){return pilot.tasks.filter(t=>t.status==="Complete").length;}
  function syncTelemetryBaseline(){try{const raw=JSON.parse(localStorage.getItem("coursebuild.telemetry.v1")||"null");if(!raw)return;raw.assumptions ||= {};raw.assumptions.architectureMinutes=Number(pilot.baseline.architectureMinutes||0);raw.assumptions.contentPerItemMinutes=Number(pilot.baseline.contentMinutes||0);raw.assumptions.canvasPerItemMinutes=Number(pilot.baseline.canvasMinutes||0);raw.assumptions.versionPerItemMinutes=Number(pilot.baseline.versionMinutes||0);localStorage.setItem("coursebuild.telemetry.v1",JSON.stringify(raw));window.CourseBuildTelemetry?.render?.();}catch(e){}
  }
  function scale(name,label,value){return `<label>${esc(label)}<div class="scale"><input name="${name}" type="range" min="1" max="5" value="${Number(value||3)}"><span>${Number(value||3)}/5</span></div></label>`;}
  function renderPilot(){
    const total=pilot.tasks.length,done=completed();
    $("#pilot").innerHTML=`<div class="section-head"><div><p class="eyebrow">External Pilot</p><h2>Test CourseBuild like a product, not a demo.</h2><p>This guided protocol captures who tested, the manual baseline, task completion, qualitative feedback, and a standardized evidence package.</p></div>${badge(done===total?"Pilot complete":`${done}/${total} tasks`)}</div>
    <div class="cards"><article class="card"><span>Pilot ID</span><strong class="status-word">${esc(pilot.pilotId)}</strong></article><article class="card"><span>Tasks complete</span><strong>${done}/${total}</strong></article><article class="card"><span>Status</span><strong class="status-word">${pilot.completedAt?"Complete":"In progress"}</strong></article></div>
    <article class="panel"><h3>1. Participant + consent</h3><p class="hint">Pilot data stays in this browser until the participant exports it. Do not enter student records, grades, protected student information, API keys, or secrets.</p><form id="pilotParticipant" class="form"><div class="grid two"><label>Name or participant code<input name="name" value="${esc(pilot.participant.name)}"></label><label>Role<select name="role"><option>Faculty</option><option>Instructional Designer</option><option>Academic Administrator</option><option>Other</option></select></label><label>Institution<input name="institution" value="${esc(pilot.participant.institution)}"></label><label>Discipline<input name="discipline" value="${esc(pilot.participant.discipline)}"></label><label>Canvas experience<select name="canvasExperience"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label></div><label class="pilot-consent"><input name="acknowledged" type="checkbox" ${pilot.consent.acknowledged?"checked":""}> I understand this is a product pilot, I should use non-sensitive course materials, and my local pilot evidence can be exported for evaluation only if I choose to share it.</label><button class="primary">Save pilot profile</button></form></article>
    <article class="panel"><h3>2. Manual baseline</h3><p>Estimate your normal manual effort before using CourseBuild. These are participant-supplied baselines, not CourseBuild claims.</p><form id="pilotBaseline" class="form"><div class="grid two"><label>Course architecture / planning (minutes)<input name="architectureMinutes" type="number" min="0" value="${Number(pilot.baseline.architectureMinutes||0)}"></label><label>Draft + review per LMS item (minutes)<input name="contentMinutes" type="number" min="0" value="${Number(pilot.baseline.contentMinutes||0)}"></label><label>Canvas assembly per item (minutes)<input name="canvasMinutes" type="number" min="0" value="${Number(pilot.baseline.canvasMinutes||0)}"></label><label>Delivery-version adaptation per item (minutes)<input name="versionMinutes" type="number" min="0" value="${Number(pilot.baseline.versionMinutes||0)}"></label></div><label>Baseline notes<textarea name="notes" rows="3">${esc(pilot.baseline.notes)}</textarea></label><button>Save baseline</button></form></article>
    <article class="panel"><h3>3. Guided tasks</h3><div class="pilot-task-list">${pilot.tasks.map((t,i)=>`<div class="pilot-task"><div><span class="module-number">${i+1}</span></div><div><b>${esc(t.title)}</b><p>${esc(t.help)}</p>${t.completedAt?`<small>Completed ${esc(new Date(t.completedAt).toLocaleString())}</small>`:""}</div><div class="pilot-task-actions">${badge(t.status)}<button data-pilot-start="${t.id}" ${t.status==="Complete"?"disabled":""}>Start</button><button data-pilot-complete="${t.id}" ${t.status==="Complete"?"disabled":""}>Mark complete</button></div></div>`).join("")}</div></article>
    <article class="panel"><h3>4. Pilot reflection</h3><form id="pilotFeedback" class="form"><div class="grid two">${scale("usefulness","CourseBuild was useful",pilot.feedback.usefulness)}${scale("ease","The workflow was easy to understand",pilot.feedback.ease)}${scale("control","I felt in control of AI-generated changes",pilot.feedback.control)}${scale("confidence","I would trust CourseBuild in a real course workflow",pilot.feedback.confidence)}</div><div class="grid two"><label>Would you use CourseBuild again?<select name="wouldUseAgain"><option value="">Select…</option><option>Yes</option><option>Maybe</option><option>No</option></select></label><label>Would you recommend a pilot to a colleague?<select name="wouldRecommend"><option value="">Select…</option><option>Yes</option><option>Maybe</option><option>No</option></select></label></div><label>Most valuable part<textarea name="bestPart" rows="2">${esc(pilot.feedback.bestPart)}</textarea></label><label>Biggest friction<textarea name="friction" rows="2">${esc(pilot.feedback.friction)}</textarea></label><label>What is missing?<textarea name="missing" rows="2">${esc(pilot.feedback.missing)}</textarea></label><label>Other notes<textarea name="notes" rows="2">${esc(pilot.feedback.notes)}</textarea></label><button class="primary">Save reflection</button></form></article>
    <article class="panel"><h3>5. Evidence package</h3><p>Export a single JSON file that combines the pilot profile, baseline, guided task progress, reflection, CourseBuild state summary, reconciliation summaries, and local telemetry.</p><div class="actions"><button id="completePilot" ${!pilot.consent.acknowledged||done<total?"disabled":""}>Complete pilot</button><button id="exportPilot" class="primary">Export pilot evidence JSON</button><button id="resetPilot">Start new pilot</button></div></article>`;
    const pf=$("#pilotParticipant");pf.elements.role.value=pilot.participant.role;pf.elements.canvasExperience.value=pilot.participant.canvasExperience;pf.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);pilot.participant={name:String(f.get("name")||"").trim(),role:String(f.get("role")||"Faculty"),institution:String(f.get("institution")||"").trim(),discipline:String(f.get("discipline")||"").trim(),canvasExperience:String(f.get("canvasExperience")||"Intermediate")};pilot.consent.acknowledged=f.get("acknowledged")==="on";pilot.consent.completedAt=pilot.consent.acknowledged?new Date().toISOString():"";persist();renderPilot();};
    $("#pilotBaseline").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);for(const k of ["architectureMinutes","contentMinutes","canvasMinutes","versionMinutes"])pilot.baseline[k]=Math.max(0,Number(f.get(k)||0));pilot.baseline.notes=String(f.get("notes")||"").trim();persist();syncTelemetryBaseline();setTask("baseline","Complete");toast("Manual baseline saved.");};
    document.querySelectorAll("[data-pilot-start]").forEach(b=>b.onclick=()=>setTask(b.dataset.pilotStart,"In progress"));document.querySelectorAll("[data-pilot-complete]").forEach(b=>b.onclick=()=>setTask(b.dataset.pilotComplete,"Complete"));
    const ff=$("#pilotFeedback");for(const k of ["wouldUseAgain","wouldRecommend"])ff.elements[k].value=pilot.feedback[k]||"";ff.querySelectorAll('input[type="range"]').forEach(r=>r.oninput=()=>r.nextElementSibling.textContent=`${r.value}/5`);ff.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);for(const k of ["usefulness","ease","control","confidence"])pilot.feedback[k]=Number(f.get(k)||0);for(const k of ["wouldUseAgain","wouldRecommend","bestPart","friction","missing","notes"])pilot.feedback[k]=String(f.get(k)||"").trim();persist();setTask("feedback","Complete");toast("Pilot reflection saved.");};
    $("#completePilot").onclick=()=>{pilot.completedAt=new Date().toISOString();persist();window.CourseBuildTelemetry?.event?.("pilot_completed",{pilotId:pilot.pilotId,participantRole:pilot.participant.role});renderPilot();toast("Pilot marked complete.");};
    $("#exportPilot").onclick=exportPilot;$("#resetPilot").onclick=()=>{pilot=fresh();persist();renderPilot();toast("New pilot started.");};
  }
  function exportPilot(){let telemetry=null;try{telemetry=JSON.parse(localStorage.getItem("coursebuild.telemetry.v1")||"null");}catch(e){}const versionSummaries=(data.versions||[]).map(v=>({id:v.id,name:v.name,approvalStatus:v.approvalStatus,syncStatus:v.syncStatus,baseRevision:v.baseRevision,reconciliation:v.reconciliation||null,materialization:v.materialization?.lastRun||null}));const report={schema:"coursebuild-pilot-evidence-v1",exportedAt:new Date().toISOString(),pilot,course:{id:data.profile?.id||"",code:data.profile?.code||"",title:data.profile?.title||"",institution:data.profile?.institution||"",modules:(data.modules||[]).length,items:(data.items||[]).length,architectureStatus:data.architecture?.status||"",masterRevision:data.master?.revision||0},versions:versionSummaries,telemetry};const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`coursebuild-pilot-${pilot.pilotId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);window.CourseBuildTelemetry?.event?.("pilot_exported",{pilotId:pilot.pilotId,tasksComplete:completed()});}
  window.renderPilot=renderPilot;
  renderPilot();
})();
