/* CourseBuild v0.12 · local multi-project persistence + migration adapter */
(function(){
  const INDEX_KEY="coursebuild.projects.v1";
  const ACTIVE_KEY="coursebuild.projects.active.v1";
  const LEGACY_COURSE_KEY="coursebuild.pilot.v4";
  const TELEMETRY_KEY="coursebuild.telemetry.v1";
  const EXTERNAL_PILOT_KEY="coursebuild.externalPilot.v1";
  const PROJECT_SCHEMA="coursebuild-project-v1";

  const readJson=(key,fallback=null)=>{try{return JSON.parse(localStorage.getItem(key)||"null")??fallback;}catch(e){return fallback;}};
  const now=()=>new Date().toISOString();
  const projectKey=id=>`coursebuild.project.v1.${id}`;
  const newId=()=>`project-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  function projectNameFromState(state){return state?.profile?.code&&state?.profile?.title?`${state.profile.code} · ${state.profile.title}`:state?.profile?.title||state?.profile?.code||"Untitled Course";}
  function readIndex(){const i=readJson(INDEX_KEY,[]);return Array.isArray(i)?i:[];}
  function writeIndex(i){localStorage.setItem(INDEX_KEY,JSON.stringify(i));}
  function activeId(){return localStorage.getItem(ACTIVE_KEY)||"";}
  function setActive(id){localStorage.setItem(ACTIVE_KEY,id);}
  function envelopeFromCurrent(id,existing={}){return{schema:PROJECT_SCHEMA,id,name:existing.name||projectNameFromState(data),createdAt:existing.createdAt||now(),updatedAt:now(),courseState:clone(data),telemetry:readJson(TELEMETRY_KEY,null),externalPilot:readJson(EXTERNAL_PILOT_KEY,null)};}
  function saveEnvelope(env){localStorage.setItem(projectKey(env.id),JSON.stringify(env));const index=readIndex();const pos=index.findIndex(x=>x.id===env.id);const meta={id:env.id,name:env.name||projectNameFromState(env.courseState),createdAt:env.createdAt,updatedAt:env.updatedAt,courseCode:env.courseState?.profile?.code||"",courseTitle:env.courseState?.profile?.title||""};if(pos>=0)index[pos]=meta;else index.push(meta);index.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));writeIndex(index);}
  function restoreEnvelope(env){if(!env||env.schema!==PROJECT_SCHEMA||!env.courseState)throw new Error("Invalid CourseBuild project file.");localStorage.setItem(LEGACY_COURSE_KEY,JSON.stringify(env.courseState));if(env.telemetry)localStorage.setItem(TELEMETRY_KEY,JSON.stringify(env.telemetry));else localStorage.removeItem(TELEMETRY_KEY);if(env.externalPilot)localStorage.setItem(EXTERNAL_PILOT_KEY,JSON.stringify(env.externalPilot));else localStorage.removeItem(EXTERNAL_PILOT_KEY);setActive(env.id);saveEnvelope(env);}
  function ensureMigrated(){let id=activeId(),index=readIndex();if(id&&readJson(projectKey(id),null)){const current=readJson(projectKey(id),null);current.courseState=clone(data);current.telemetry=readJson(TELEMETRY_KEY,current.telemetry||null);current.externalPilot=readJson(EXTERNAL_PILOT_KEY,current.externalPilot||null);current.updatedAt=now();saveEnvelope(current);return id;}id=newId();const env=envelopeFromCurrent(id,{name:projectNameFromState(data)});saveEnvelope(env);setActive(id);return id;}
  let currentProjectId=ensureMigrated();
  const originalSave=save;
  save=function(){originalSave();const existing=readJson(projectKey(currentProjectId),{});const env=envelopeFromCurrent(currentProjectId,existing);env.name=existing.name||projectNameFromState(data);saveEnvelope(env);renderProjectChrome();};

  function snapshotCurrent(){const existing=readJson(projectKey(currentProjectId),{});const env=envelopeFromCurrent(currentProjectId,existing);env.name=existing.name||projectNameFromState(data);saveEnvelope(env);return env;}
  function createProject(){snapshotCurrent();const title=prompt("Project name", "New CourseBuild project");if(title===null)return;const id=newId();const state=clone(window.COURSEBUILD_SAMPLE);state.profile={...state.profile,id:id,code:"",title:title.trim()||"Untitled Course",institution:"",description:"",outcomes:[],policies:[]};state.modules=[];state.items=[];state.source={text:"",digest:"",fileName:"",importedAt:"",importMode:"new project"};state.architecture={status:"Draft",approvedAt:"",approvedBy:"Instructor"};state.master={revision:0,approvedAt:"",signature:""};state.versions=[];const env={schema:PROJECT_SCHEMA,id,name:title.trim()||"Untitled Course",createdAt:now(),updatedAt:now(),courseState:state,telemetry:null,externalPilot:null};saveEnvelope(env);restoreEnvelope(env);location.reload();}
  function switchProject(id){if(!id||id===currentProjectId)return;snapshotCurrent();const env=readJson(projectKey(id),null);if(!env)return toast("Project could not be loaded.");restoreEnvelope(env);location.reload();}
  function renameProject(){const env=readJson(projectKey(currentProjectId),null);if(!env)return;const name=prompt("Rename project",env.name||projectNameFromState(env.courseState));if(name===null||!name.trim())return;env.name=name.trim();env.updatedAt=now();saveEnvelope(env);renderProjects();renderProjectChrome();}
  function duplicateProject(){const source=snapshotCurrent(),id=newId();const copy=clone(source);copy.id=id;copy.name=`${source.name||projectNameFromState(source.courseState)} Copy`;copy.createdAt=now();copy.updatedAt=now();copy.courseState.profile={...copy.courseState.profile,id};saveEnvelope(copy);restoreEnvelope(copy);location.reload();}
  function exportProject(){const env=snapshotCurrent();const blob=new Blob([JSON.stringify(env,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`coursebuild-project-${env.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);window.CourseBuildTelemetry?.event?.("project_exported",{projectId:env.id});}
  async function importProject(file){if(!file)return;let env;try{env=JSON.parse(await file.text());}catch(e){return toast("That project file is not valid JSON.");}if(env.schema!==PROJECT_SCHEMA||!env.courseState)return toast("That file is not a CourseBuild project export.");snapshotCurrent();const existingIds=new Set(readIndex().map(x=>x.id));if(!env.id||existingIds.has(env.id))env.id=newId();env.createdAt=env.createdAt||now();env.updatedAt=now();env.name=env.name||projectNameFromState(env.courseState);saveEnvelope(env);restoreEnvelope(env);window.CourseBuildTelemetry?.event?.("project_imported",{projectId:env.id});location.reload();}
  function deleteProject(id){const index=readIndex();if(index.length<=1)return toast("CourseBuild keeps at least one project.");const meta=index.find(x=>x.id===id);if(!meta)return;if(!confirm(`Delete local project “${meta.name}”? Export a backup first if you need it later.`))return;localStorage.removeItem(projectKey(id));writeIndex(index.filter(x=>x.id!==id));if(id===currentProjectId){const next=readIndex()[0];const env=readJson(projectKey(next.id),null);restoreEnvelope(env);location.reload();}renderProjects();}
  function renderProjectChrome(){const host=document.querySelector(".topbar");if(!host)return;let node=document.querySelector("#projectChrome");if(!node){node=document.createElement("div");node.id="projectChrome";node.className="project-chrome";host.appendChild(node);}const env=readJson(projectKey(currentProjectId),{}),index=readIndex();node.innerHTML=`<label>Project<select id="projectSwitcher">${index.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("")}</select></label><button id="newProjectQuick">+ New</button>`;const sel=node.querySelector("#projectSwitcher");sel.value=currentProjectId;sel.onchange=()=>switchProject(sel.value);node.querySelector("#newProjectQuick").onclick=createProject;}
  function renderProjects(){const host=$("#projects");if(!host)return;const index=readIndex();host.innerHTML=`<div class="section-head"><div><p class="eyebrow">Projects</p><h2>Your CourseBuild workspace.</h2><p>Each project keeps its course state plus the latest local telemetry and external-pilot context. v0.12 still stores projects in this browser, with export/import as the migration and backup path.</p></div>${badge(`${index.length} project${index.length===1?"":"s"}`)}</div><div class="actions"><button id="createProject" class="primary">+ New project</button><button id="importProjectBtn">Import project JSON</button><input id="importProjectFile" type="file" accept="application/json,.json" hidden><button id="exportProject">Export current project</button><button id="renameProject">Rename current</button><button id="duplicateProject">Duplicate current</button></div><div class="project-grid">${index.map(x=>`<article class="panel project-card ${x.id===currentProjectId?"active-project":""}"><div><p class="eyebrow">${x.id===currentProjectId?"Current project":"Saved project"}</p><h3>${esc(x.name)}</h3><p>${esc([x.courseCode,x.courseTitle].filter(Boolean).join(" · ")||"No course profile yet")}</p><small>Updated ${esc(new Date(x.updatedAt).toLocaleString())}</small></div><div class="actions"><button data-open-project="${x.id}" ${x.id===currentProjectId?"disabled":""}>Open</button><button data-delete-project="${x.id}">Delete local</button></div></article>`).join("")}</div><article class="panel"><h3>Storage boundary</h3><p>This pilot uses a local storage adapter. The project envelope is intentionally shaped so a future managed database can replace the local provider without changing the CourseBuild course model.</p><p class="hint">Exported project files may contain course content, telemetry, and pilot notes. Treat them as course-development records and do not include protected student information or secrets.</p></article>`;
    $("#createProject").onclick=createProject;$("#exportProject").onclick=exportProject;$("#renameProject").onclick=renameProject;$("#duplicateProject").onclick=duplicateProject;$("#importProjectBtn").onclick=()=>$("#importProjectFile").click();$("#importProjectFile").onchange=e=>importProject(e.target.files?.[0]);document.querySelectorAll("[data-open-project]").forEach(b=>b.onclick=()=>switchProject(b.dataset.openProject));document.querySelectorAll("[data-delete-project]").forEach(b=>b.onclick=()=>deleteProject(b.dataset.deleteProject));
  }
  window.CourseBuildProjects={schema:PROJECT_SCHEMA,currentId:()=>currentProjectId,list:readIndex,snapshot:snapshotCurrent,render:renderProjects};
  renderProjectChrome();renderProjects();
})();
