const TELEMETRY_KEY="coursebuild.telemetry.v1";
const DEFAULT_MANUAL_MINUTES={architecture:180,itemGeneration:25,itemReview:10,canvasPublish:8,versionPlan:60};
let telemetry=JSON.parse(localStorage.getItem(TELEMETRY_KEY)||"null")||{sessionStartedAt:new Date().toISOString(),events:[],benchmarks:{...DEFAULT_MANUAL_MINUTES}};
function telemetrySave(){localStorage.setItem(TELEMETRY_KEY,JSON.stringify(telemetry));}
function trackEvent(type,meta={}){telemetry.events.push({id:`evt-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,type,at:new Date().toISOString(),courseId:data?.profile?.id||"course",masterRevision:data?.master?.revision||null,...meta});telemetrySave();renderTelemetry();}
function durationMs(start){return Math.max(0,Date.now()-start);}
function eventCount(type){return telemetry.events.filter(e=>e.type===type).length;}
function sumField(type,field){return telemetry.events.filter(e=>e.type===type).reduce((n,e)=>n+Number(e[field]||0),0);}
function firstEvent(type){return telemetry.events.find(e=>e.type===type);}
function lastEvent(type){return [...telemetry.events].reverse().find(e=>e.type===type);}
function elapsedMinutes(a,b){if(!a||!b)return null;return Math.max(0,(new Date(b.at)-new Date(a.at))/60000);}
function benchmarkSummary(){
  const architectureRuns=eventCount("architecture_generated"), itemGenerated=eventCount("item_generated"), itemApproved=eventCount("item_approved"), canvasCreated=telemetry.events.filter(e=>e.type==="canvas_publish"&&e.operation==="created").length, canvasUpdated=telemetry.events.filter(e=>e.type==="canvas_publish"&&e.operation==="updated").length, versions=eventCount("version_generated");
  const manual=architectureRuns*telemetry.benchmarks.architecture+itemGenerated*telemetry.benchmarks.itemGeneration+itemApproved*telemetry.benchmarks.itemReview+(canvasCreated+canvasUpdated)*telemetry.benchmarks.canvasPublish+versions*telemetry.benchmarks.versionPlan;
  const measured=(sumField("architecture_generated","durationMs")+sumField("item_generated","durationMs")+sumField("canvas_publish","durationMs")+sumField("version_generated","durationMs"))/60000;
  const firstSource=firstEvent("source_imported")||firstEvent("source_saved"), firstArchitecture=firstEvent("architecture_generated");
  return {architectureRuns,itemGenerated,itemApproved,canvasCreated,canvasUpdated,versions,architectureEdits:eventCount("architecture_edit"),approvalCycles:eventCount("architecture_approved")+eventCount("item_approved")+eventCount("version_approved"),failures:eventCount("failure"),manualMinutes:manual,measuredMinutes:measured,estimatedSavedMinutes:Math.max(0,manual-measured),timeToArchitecture:elapsedMinutes(firstSource,firstArchitecture)};
}
function renderTelemetry(){
  const host=document.querySelector("#telemetry"); if(!host)return; const s=benchmarkSummary();
  host.innerHTML=`<div class="section-head"><div><p class="eyebrow">Pilot Evidence</p><h2>Measure the work CourseBuild removes.</h2><p>Telemetry stays in this browser for the pilot. No third-party analytics are used.</p></div>${badge(`${telemetry.events.length} events`)}</div>
  <div class="cards"><article class="card"><span>Estimated time avoided</span><strong>${(s.estimatedSavedMinutes/60).toFixed(1)}h</strong></article><article class="card"><span>Architecture edits</span><strong>${s.architectureEdits}</strong></article><article class="card"><span>Failures</span><strong>${s.failures}</strong></article></div>
  <div class="grid two"><article class="panel"><h3>Pilot benchmark</h3><dl><dt>Time to first architecture</dt><dd>${s.timeToArchitecture==null?"Not measured yet":s.timeToArchitecture.toFixed(1)+" min"}</dd><dt>Content generated</dt><dd>${s.itemGenerated}</dd><dt>Approval actions</dt><dd>${s.approvalCycles}</dd><dt>Canvas created</dt><dd>${s.canvasCreated}</dd><dt>Canvas updated</dt><dd>${s.canvasUpdated}</dd><dt>Delivery plans</dt><dd>${s.versions}</dd><dt>Measured API/workflow time</dt><dd>${s.measuredMinutes.toFixed(1)} min</dd><dt>Manual baseline</dt><dd>${(s.manualMinutes/60).toFixed(1)} hr</dd></dl></article>
  <article class="panel"><h3>Manual baseline assumptions</h3><p class="hint">Editable pilot assumptions. These are not claims; replace them with observed manual benchmarks during testing.</p><form id="benchmarkForm" class="form compact-form">${[["architecture","Manual architecture build (min)"],["itemGeneration","Manual LMS item drafting (min/item)"],["itemReview","Manual review/assembly (min/item)"],["canvasPublish","Manual Canvas assembly (min/item)"],["versionPlan","Manual delivery-version adaptation (min/version)"]].map(([k,l])=>`<label>${l}<input name="${k}" type="number" min="0" value="${Number(telemetry.benchmarks[k]||0)}"></label>`).join("")}<button>Save assumptions</button></form></article></div>
  <article class="panel"><div class="section-head"><div><h3>Event log</h3><p>Useful for pilot debriefs and failure analysis.</p></div><div class="actions"><button id="exportTelemetry">Export JSON</button><button id="resetTelemetry">Reset telemetry</button></div></div><div class="telemetry-log">${telemetry.events.slice(-30).reverse().map(e=>`<div class="telemetry-row"><span>${esc(new Date(e.at).toLocaleTimeString())}</span><b>${esc(e.type.replaceAll("_"," "))}</b><span>${esc(e.operation||e.versionId||e.itemId||e.moduleId||"")}</span></div>`).join("")||"<p class='muted-text'>No telemetry yet.</p>"}</div></article>`;
  const form=document.querySelector("#benchmarkForm"); if(form)form.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);Object.keys(telemetry.benchmarks).forEach(k=>telemetry.benchmarks[k]=Number(f.get(k)||0));telemetrySave();renderTelemetry();toast("Benchmark assumptions saved.");};
  const exp=document.querySelector("#exportTelemetry"); if(exp)exp.onclick=exportTelemetry;
  const reset=document.querySelector("#resetTelemetry"); if(reset)reset.onclick=()=>{telemetry={sessionStartedAt:new Date().toISOString(),events:[],benchmarks:{...DEFAULT_MANUAL_MINUTES}};telemetrySave();renderTelemetry();toast("Pilot telemetry reset.");};
}
function exportTelemetry(){const report={exportedAt:new Date().toISOString(),course:{id:data?.profile?.id,title:data?.profile?.title,code:data?.profile?.code},summary:benchmarkSummary(),benchmarks:telemetry.benchmarks,events:telemetry.events};const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`coursebuild-pilot-${data?.profile?.code||"course"}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
function wrapAsync(name,startType,successType,metaFn){const original=window[name];if(typeof original!=="function")return;window[name]=async function(...args){const start=Date.now();if(startType)trackEvent(startType,metaFn?metaFn(args):{});try{const result=await original.apply(this,args);trackEvent(successType,{durationMs:durationMs(start),...(metaFn?metaFn(args):{})});return result;}catch(err){trackEvent("failure",{operation:name,durationMs:durationMs(start),message:String(err?.message||err)});throw err;}};}
function wrapSync(name,eventType,metaFn){const original=window[name];if(typeof original!=="function")return;window[name]=function(...args){const before=JSON.stringify(data?.architecture||{});const result=original.apply(this,args);trackEvent(eventType,{...(metaFn?metaFn(args):{}),architectureChanged:before!==JSON.stringify(data?.architecture||{})});return result;};}
wrapAsync("generateArchitecture","architecture_generation_started","architecture_generated");
wrapAsync("generateItem","item_generation_started","item_generated",args=>({itemId:args[0]}));
wrapAsync("generateVersion",null,"version_generated",args=>({versionId:args[0]}));
wrapSync("approveArchitecture","architecture_approved");
wrapSync("approveItem","item_approved",args=>({itemId:args[0]}));
wrapSync("approveVersion","version_approved",args=>({versionId:args[0]}));
["patchItem","patchModule","addModule","addItem","deleteItem","deleteModule","moveModule"].forEach(n=>wrapSync(n,"architecture_edit",args=>({operation:n,targetId:args[0]})));
const originalHandleFile=window.handleFile;if(typeof originalHandleFile==="function")window.handleFile=async function(file){if(file)trackEvent("source_imported",{fileName:file.name,mimeType:file.type,size:file.size});try{return await originalHandleFile.apply(this,arguments);}catch(err){trackEvent("failure",{operation:"source_import",message:String(err?.message||err)});throw err;}};
const originalSendApproved=window.sendApproved;if(typeof originalSendApproved==="function")window.sendApproved=async function(){const before=new Map((data.items||[]).map(i=>[i.id,{status:i.status,canvasId:i.canvasId}]));const start=Date.now();try{const out=await originalSendApproved.apply(this,arguments);(data.items||[]).forEach(i=>{const old=before.get(i.id);if(old?.status==="Approved"&&i.status==="Sent")trackEvent("canvas_publish",{itemId:i.id,operation:old.canvasId?"updated":"created",durationMs:durationMs(start)});});return out;}catch(err){trackEvent("failure",{operation:"canvas_publish",message:String(err?.message||err),durationMs:durationMs(start)});throw err;}};
const baseRenderAll=window.renderAll;if(typeof baseRenderAll==="function")window.renderAll=function(){const r=baseRenderAll.apply(this,arguments);renderTelemetry();return r;};
document.querySelectorAll("[data-view]").forEach(b=>{const previous=b.onclick;b.onclick=()=>{previous?.();if(b.dataset.view==="telemetry")renderTelemetry();};});
trackEvent("pilot_session_loaded",{userAgent:navigator.userAgent.slice(0,160)});
renderTelemetry();